// DGT 2026 — Preguntas nuevas categorías
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const NEW_CATEGORY_QUESTIONS: any[] = [

  // ─── LIGHTING (Alumbrado y Luces) ────────────────────────────────────────

  {
    prompt: '¿A qué distancia mínima debes cambiar de luces largas a luces de cruce cuando te aproximas a un vehículo en sentido contrario?',
    explanation: 'El Reglamento General de Circulación establece que las luces largas deben cambiarse a luces de cruce al aproximarse a otro vehículo en sentido contrario a una distancia mínima de 150 metros, para no deslumbrar al conductor de enfrente.',
    category: 'LIGHTING',
    difficulty: 2,
    isTrap: false,
    tags: ['luces', 'cruce', 'encuentro', 'distancia'],
    options: [
      { text: '100 metros', isCorrect: false },
      { text: '150 metros', isCorrect: true },
      { text: '200 metros', isCorrect: false },
      { text: '50 metros', isCorrect: false },
    ],
  },
  {
    prompt: 'Cuando sigues a otro vehículo por la noche, ¿a qué distancia mínima debes reducir a luces de cruce para no deslumbrarlo por el retrovisor?',
    explanation: 'Al circular detrás de otro vehículo se deben usar luces de cruce si la distancia es inferior a 100 metros, ya que las luces largas se reflejan en sus retrovisores y pueden deslumbrar al conductor precedente.',
    category: 'LIGHTING',
    difficulty: 2,
    isTrap: false,
    tags: ['luces', 'cruce', 'seguimiento', 'distancia'],
    options: [
      { text: '150 metros', isCorrect: false },
      { text: '50 metros', isCorrect: false },
      { text: '100 metros', isCorrect: true },
      { text: '75 metros', isCorrect: false },
    ],
  },
  {
    prompt: '¿En cuál de estas situaciones está PROHIBIDO usar las luces de carretera (largas)?',
    explanation: 'Las luces de carretera (largas) están prohibidas dentro de poblado, cuando hay iluminación suficiente de la vía, en niebla o lluvia intensa (por el efecto pantalla que producen al refractarse en las partículas de agua), y siempre que puedan deslumbrar a otros conductores.',
    category: 'LIGHTING',
    difficulty: 2,
    isTrap: false,
    tags: ['luces largas', 'prohibición', 'niebla'],
    options: [
      { text: 'En carretera convencional sin iluminación y sin tráfico', isCorrect: false },
      { text: 'En autopista de noche sin otros vehículos cercanos', isCorrect: false },
      { text: 'En niebla densa, porque producen efecto pantalla', isCorrect: true },
      { text: 'En curvas sin visibilidad cuando no hay tráfico', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuándo es obligatorio encender la luz antiniebla trasera?',
    explanation: 'La luz antiniebla trasera solo es obligatoria cuando la visibilidad es inferior a 50 metros por causa de niebla, lluvia muy intensa, nevada o nube de polvo. Usarla con visibilidad normal puede deslumbrar a los conductores de detrás.',
    category: 'LIGHTING',
    difficulty: 2,
    isTrap: false,
    tags: ['antiniebla', 'trasera', 'visibilidad', '50m'],
    options: [
      { text: 'Siempre que llueva, aunque sea levemente', isCorrect: false },
      { text: 'Cuando la visibilidad es inferior a 50 metros', isCorrect: true },
      { text: 'Cuando la visibilidad es inferior a 100 metros', isCorrect: false },
      { text: 'En cualquier condición de niebla o lluvia', isCorrect: false },
    ],
  },
  {
    prompt: '¿Para qué situaciones está previsto el uso de las luces antiniebla delanteras?',
    explanation: 'Las luces antiniebla delanteras están diseñadas para mejorar la visión del conductor en condiciones de niebla intensa, lluvia muy fuerte o nevada, ya que su haz bajo y amplio ilumina la calzada reduciendo el efecto de deslumbramiento en las partículas en suspensión.',
    category: 'LIGHTING',
    difficulty: 1,
    isTrap: false,
    tags: ['antiniebla', 'delantera', 'lluvia', 'nieve'],
    options: [
      { text: 'Para circular de noche en carretera sin iluminación', isCorrect: false },
      { text: 'En lluvia intensa, niebla densa o nevada', isCorrect: true },
      { text: 'Como sustituto de las luces de cruce en ciudad', isCorrect: false },
      { text: 'Únicamente en autopistas y autovías', isCorrect: false },
    ],
  },
  {
    prompt: '¿Pueden utilizarse las luces de posición como único sistema de iluminación cuando se circula de noche?',
    explanation: 'Las luces de posición (luz de estacionamiento o de ciudad) NO son suficientes para circular de noche. Son un complemento de las luces de cruce o de carretera y sirven para que el vehículo sea visible, pero no iluminan la calzada lo suficiente para conducir.',
    category: 'LIGHTING',
    difficulty: 2,
    isTrap: true,
    tags: ['posición', 'estacionamiento', 'noche', 'circulación'],
    options: [
      { text: 'Sí, dentro de poblado con iluminación pública suficiente', isCorrect: false },
      { text: 'Sí, cuando la velocidad no supera los 50 km/h', isCorrect: false },
      { text: 'No, nunca son suficientes para circular; son solo complemento', isCorrect: true },
      { text: 'Sí, si la vía tiene buena iluminación artificial', isCorrect: false },
    ],
  },
  {
    prompt: '¿En qué caso está justificado el uso de las luces de emergencia (destellantes o hazards) mientras el vehículo está en marcha?',
    explanation: 'Las luces de emergencia (hazards) se usan cuando el vehículo representa un peligro o pasa por una situación excepcional: circulación muy lenta por avería inminente, cola en autopista, descenso de velocidad repentino, o para avisar a los vehículos que siguen de un peligro adelante. No deben usarse para aparcar en doble fila ni indicar que se frena en maniobra normal.',
    category: 'LIGHTING',
    difficulty: 2,
    isTrap: true,
    tags: ['emergencia', 'hazards', 'destellantes'],
    options: [
      { text: 'Para aparcar brevemente en doble fila', isCorrect: false },
      { text: 'Al iniciar la marcha desde el arcén', isCorrect: false },
      { text: 'Cuando el vehículo se detiene bruscamente en autopista por retención', isCorrect: true },
      { text: 'Para indicar que se va a girar a la derecha en ciudad', isCorrect: false },
    ],
  },
  {
    prompt: '¿Es obligatorio encender las luces de cruce al circular por un túnel, aunque haya iluminación artificial?',
    explanation: 'Sí. El Reglamento General de Circulación obliga a encender las luces de cruce en todos los túneles, independientemente de si están iluminados artificialmente. El motivo es que la iluminación del túnel puede no ser uniforme y las luces aumentan la visibilidad del vehículo para los demás.',
    category: 'LIGHTING',
    difficulty: 2,
    isTrap: true,
    tags: ['túnel', 'cruce', 'obligatorio'],
    options: [
      { text: 'No, solo si el túnel está oscuro o mal iluminado', isCorrect: false },
      { text: 'Sí, siempre, aunque haya iluminación artificial', isCorrect: true },
      { text: 'Solo si el túnel supera los 300 metros de longitud', isCorrect: false },
      { text: 'Solo de noche o en condiciones de escasa visibilidad', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué son las luces de gálibo y qué vehículos las llevan?',
    explanation: 'Las luces de gálibo son pequeñas luces situadas en los extremos de la parte más alta del vehículo para indicar su anchura y altura totales. Son obligatorias en vehículos de más de 2,10 metros de anchura o con remolques de gran tamaño (camiones, autobuses, vehículos especiales). No son habituales en turismos.',
    category: 'LIGHTING',
    difficulty: 3,
    isTrap: false,
    tags: ['gálibo', 'luces', 'camiones', 'anchura'],
    options: [
      { text: 'Luces parpadeantes para indicar un peligro en la calzada', isCorrect: false },
      { text: 'Luces que señalan la anchura y altura en vehículos de gran tamaño', isCorrect: true },
      { text: 'Luces de cortesía que se encienden al abrir las puertas', isCorrect: false },
      { text: 'Luces de posición que se colocan en el maletero del turismo', isCorrect: false },
    ],
  },
  {
    prompt: 'Conduces de noche con lluvia intensa. ¿Qué luces debes usar?',
    explanation: 'Con lluvia intensa de noche se deben usar las luces de cruce (cortas) y, si la visibilidad baja de 50 metros, también la antiniebla trasera. Las luces largas están contraindicadas porque crean efecto pantalla al refractarse en las gotas de agua, reduciendo la visión.',
    category: 'LIGHTING',
    difficulty: 2,
    isTrap: true,
    tags: ['lluvia', 'noche', 'cruce', 'largas'],
    options: [
      { text: 'Luces largas para ver mejor a mayor distancia', isCorrect: false },
      { text: 'Luces de cruce, y antiniebla trasera si visibilidad < 50 m', isCorrect: true },
      { text: 'Solo luces de posición si la vía tiene iluminación pública', isCorrect: false },
      { text: 'Luces largas y antiniebla delantera simultáneamente', isCorrect: false },
    ],
  },
  {
    prompt: 'Vas a circular por una vía en obras señalizada con balizamiento. ¿Qué tipo de luces usan las balizas de señalización para ser visibles de noche?',
    explanation: 'Las balizas de señalización de obras usan luces ámbar (amarillas) destellantes o fijas. El color ámbar identifica la señalización de peligro provisional, y el destello aumenta la visibilidad nocturna. No deben confundirse con las luces de emergencia de un vehículo averiado.',
    category: 'LIGHTING',
    difficulty: 3,
    isTrap: false,
    tags: ['obras', 'balizas', 'ámbar', 'señalización'],
    options: [
      { text: 'Luces rojas continuas', isCorrect: false },
      { text: 'Luces blancas fijas', isCorrect: false },
      { text: 'Luces ámbar (amarillas) destellantes o fijas', isCorrect: true },
      { text: 'Luces verdes para indicar que se puede pasar', isCorrect: false },
    ],
  },
  {
    prompt: 'Un vehículo averiado se queda parado en una vía interurbana de noche. ¿Qué luces debe encender PRIMERO antes de colocar los triángulos?',
    explanation: 'Al detenerse de emergencia, lo primero es encender las luces de emergencia (hazards) para avisar al resto del tráfico. A continuación se coloca el chaleco reflectante ANTES de salir del vehículo, y luego se colocan los triángulos de preseñalización a 50 metros delante y detrás.',
    category: 'LIGHTING',
    difficulty: 2,
    isTrap: false,
    tags: ['avería', 'emergencia', 'hazards', 'triángulos'],
    options: [
      { text: 'Luces de cruce para indicar que el vehículo está detenido', isCorrect: false },
      { text: 'Luces de emergencia (hazards) para alertar al tráfico', isCorrect: true },
      { text: 'Luces largas dirigidas hacia los vehículos que se aproximan', isCorrect: false },
      { text: 'Luces de posición para indicar la anchura del vehículo', isCorrect: false },
    ],
  },

  // ─── SAFETY_SYSTEMS (Sistemas de Seguridad) ──────────────────────────────

  {
    prompt: '¿Qué hace exactamente el sistema ABS al frenar con fuerza?',
    explanation: 'El ABS (Sistema Antibloqueo de Frenos) evita que las ruedas se bloqueen al frenar con fuerza, permitiendo al conductor mantener la dirección del vehículo durante la frenada de emergencia. La técnica correcta con ABS es pisar el freno a fondo y mantenerlo, sin bombear, y girar el volante para esquivar el obstáculo si es necesario.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 2,
    isTrap: false,
    tags: ['ABS', 'frenada', 'bloqueo', 'dirección'],
    options: [
      { text: 'Reduce la distancia de frenado a la mitad en cualquier superficie', isCorrect: false },
      { text: 'Evita el bloqueo de ruedas y permite mantener la dirección al frenar', isCorrect: true },
      { text: 'Bombea automáticamente el freno para reducir velocidad progresivamente', isCorrect: false },
      { text: 'Bloquea las ruedas delanteras para estabilizar el vehículo', isCorrect: false },
    ],
  },
  {
    prompt: 'Tu vehículo tiene ABS. ¿Cómo debes accionar el freno en una frenada de emergencia?',
    explanation: 'Con ABS, la técnica correcta es pisar el pedal de freno con toda la fuerza posible (frenada máxima) y MANTENERLO pisado. No se debe bombear el freno, ya que el propio sistema hace ese trabajo automáticamente para evitar el bloqueo de ruedas.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 2,
    isTrap: true,
    tags: ['ABS', 'frenada', 'emergencia', 'bombear'],
    options: [
      { text: 'Bombear el freno rápidamente como si no tuvieras ABS', isCorrect: false },
      { text: 'Pisar el freno a fondo y mantenerlo, sin bombear', isCorrect: true },
      { text: 'Aplicar fuerza moderada para no activar el ABS', isCorrect: false },
      { text: 'Soltar el freno a intervalos para evitar el bloqueo manual', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué sistema actúa de forma autónoma cuando detecta riesgo inminente de colisión y el conductor no reacciona?',
    explanation: 'El AEB (Frenado de Emergencia Autónomo) detecta obstáculos mediante sensores (radar, cámara, lidar) y aplica el freno automáticamente si detecta riesgo de colisión y el conductor no reacciona. Desde julio de 2022 es obligatorio en todos los vehículos nuevos vendidos en la Unión Europea.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 2,
    isTrap: false,
    tags: ['AEB', 'frenada autónoma', 'EU 2022', 'colisión'],
    options: [
      { text: 'El ESP (control de estabilidad electrónico)', isCorrect: false },
      { text: 'El ABS (sistema antibloqueo de frenos)', isCorrect: false },
      { text: 'El AEB (frenado de emergencia autónomo)', isCorrect: true },
      { text: 'El TCS (control de tracción)', isCorrect: false },
    ],
  },
  {
    prompt: 'El ESP (Electronic Stability Program) detecta que el vehículo derrapa. ¿Cómo actúa?',
    explanation: 'El ESP compara la trayectoria deseada por el conductor (medida por el ángulo del volante y la velocidad) con la trayectoria real del vehículo. Al detectar derrape, aplica el freno de forma selectiva en una o varias ruedas específicas para corregir la trayectoria, y puede también reducir el par motor.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 2,
    isTrap: false,
    tags: ['ESP', 'estabilidad', 'derrape', 'freno selectivo'],
    options: [
      { text: 'Bloquea las cuatro ruedas para frenar el vehículo lo antes posible', isCorrect: false },
      { text: 'Aumenta la potencia del motor para salir del derrape', isCorrect: false },
      { text: 'Aplica el freno selectivamente en ruedas concretas para corregir la trayectoria', isCorrect: true },
      { text: 'Desactiva el motor y activa el freno de mano automáticamente', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuándo debe ponerse el cinturón de seguridad?',
    explanation: 'El cinturón de seguridad es obligatorio para todos los ocupantes del vehículo y debe abrocharse ANTES de arrancar el motor, no una vez que el vehículo ya está en marcha. La omisión supone una infracción grave que conlleva multa y pérdida de puntos.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 1,
    isTrap: false,
    tags: ['cinturón', 'obligatorio', 'arrancar'],
    options: [
      { text: 'Una vez que el vehículo está en movimiento', isCorrect: false },
      { text: 'Solo en vías interurbanas y autopistas', isCorrect: false },
      { text: 'Antes de arrancar el motor, siempre', isCorrect: true },
      { text: 'Solo el conductor; los pasajeros en la parte trasera están exentos', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué sistema de retención es obligatorio para menores de menos de 135 cm de altura?',
    explanation: 'Los menores con altura inferior a 135 cm deben ir sujetos con un sistema de retención homologado (SRI) adecuado a su talla y peso: silla, alzador o grupo correspondiente. Es obligatorio en todos los asientos. A partir de 135 cm pueden usar el cinturón de adulto.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 1,
    isTrap: false,
    tags: ['silla infantil', 'menores', '135cm', 'retención homologado'],
    options: [
      { text: 'El cinturón de adulto si el menor tiene más de 5 años', isCorrect: false },
      { text: 'Un sistema de retención infantil homologado adecuado a su talla y peso', isCorrect: true },
      { text: 'Un arnés especial solo para el asiento delantero', isCorrect: false },
      { text: 'Ninguno si el trayecto es inferior a 10 kilómetros', isCorrect: false },
    ],
  },
  {
    prompt: '¿Puede colocarse una silla infantil orientada hacia atrás en el asiento delantero si el airbag frontal está ACTIVADO?',
    explanation: 'No. Una silla infantil orientada hacia atrás en el asiento delantero con el airbag activado es extremadamente peligrosa: en caso de activación, el airbag impacta directamente sobre la parte trasera de la silla con una fuerza capaz de causar lesiones graves o la muerte al bebé. Solo se permite si el airbag está desactivado.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 2,
    isTrap: true,
    tags: ['airbag', 'silla infantil', 'orientada atrás', 'delantero'],
    options: [
      { text: 'Sí, si el niño es menor de 12 meses', isCorrect: false },
      { text: 'Sí, el airbag solo se activa en choques muy severos', isCorrect: false },
      { text: 'No, el airbag debe estar desactivado para usar silla orientada hacia atrás', isCorrect: true },
      { text: 'Sí, el airbag se desactiva automáticamente al detectar la silla', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué hace el sistema TCS (Control de Tracción) cuando detecta que una rueda motriz patina?',
    explanation: 'El TCS (Traction Control System) detecta cuando una rueda motriz pierde adherencia y patina más rápido que las demás. Para recuperar la tracción, reduce el par motor y/o aplica el freno en esa rueda hasta que recupera agarre. Es especialmente útil en arranques en superficie resbaladiza.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 2,
    isTrap: false,
    tags: ['TCS', 'tracción', 'patinaje', 'rueda'],
    options: [
      { text: 'Aumenta la potencia del motor para que la rueda recupere tracción', isCorrect: false },
      { text: 'Reduce el par motor y/o frena la rueda que patina para recuperar adherencia', isCorrect: true },
      { text: 'Bloquea el diferencial para repartir la tracción entre ambas ruedas', isCorrect: false },
      { text: 'Desactiva el motor temporalmente para evitar el patinaje', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué función realiza el sistema LKAS (Lane Keeping Assist System)?',
    explanation: 'El LKAS (Sistema de Asistencia de Mantenimiento de Carril) usa cámaras para detectar las marcas viales y, si el vehículo se sale involuntariamente del carril sin usar el intermitente, genera correcciones en la dirección y/o avisos al conductor. Es un sistema de asistencia, no de conducción autónoma.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 3,
    isTrap: false,
    tags: ['LKAS', 'carril', 'asistencia', 'marcas viales'],
    options: [
      { text: 'Mantiene el vehículo a velocidad constante adaptándose al tráfico', isCorrect: false },
      { text: 'Detecta peatones y frena el vehículo antes de un atropello', isCorrect: false },
      { text: 'Monitoriza las marcas viales y corrige la dirección si el vehículo se sale del carril', isCorrect: true },
      { text: 'Controla la presión de los neumáticos en tiempo real', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué ventaja ofrece el crucero adaptativo (ACC) frente al crucero convencional?',
    explanation: 'El ACC (Adaptive Cruise Control) mantiene la velocidad seleccionada pero, a diferencia del crucero convencional, también regula automáticamente la distancia de seguridad con el vehículo precedente usando sensores radar/lidar. Reduce o acelera el vehículo para mantener siempre una separación segura.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 2,
    isTrap: false,
    tags: ['ACC', 'crucero adaptativo', 'distancia', 'radar'],
    options: [
      { text: 'Mantiene la velocidad exacta sin variarla en ningún caso', isCorrect: false },
      { text: 'Ajusta la velocidad automáticamente para mantener distancia de seguridad', isCorrect: true },
      { text: 'Frena de emergencia solo cuando detecta un peatón', isCorrect: false },
      { text: 'Actúa solo en autopistas y no funciona en ciudad', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué indica el TPMS cuando se enciende el testigo en el cuadro de mandos?',
    explanation: 'El TPMS (Tyre Pressure Monitoring System) es el sensor de presión de neumáticos. Cuando el testigo se enciende, indica que uno o más neumáticos tienen una presión significativamente inferior a la correcta (generalmente más del 25% por debajo). Se debe parar en lugar seguro y revisar/inflar los neumáticos.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 2,
    isTrap: false,
    tags: ['TPMS', 'presión', 'neumáticos', 'testigo'],
    options: [
      { text: 'Que el neumático está próximo a sufrir un pinchazo por desgaste del dibujo', isCorrect: false },
      { text: 'Que la temperatura de los frenos es demasiado elevada', isCorrect: false },
      { text: 'Que uno o más neumáticos tienen presión significativamente inferior a la correcta', isCorrect: true },
      { text: 'Que el vehículo lleva demasiada carga para la presión actual', isCorrect: false },
    ],
  },
  {
    prompt: 'El airbag es un sistema de retención COMPLEMENTARIO. ¿Qué significa esto para el conductor?',
    explanation: 'El airbag está diseñado para funcionar conjuntamente con el cinturón de seguridad, no en su lugar. Sin cinturón, el airbag puede causar lesiones graves porque el ocupante impacta contra él a alta velocidad. El cinturón mantiene al ocupante en posición para que el airbag ejerza su efecto amortiguador correctamente.',
    category: 'SAFETY_SYSTEMS',
    difficulty: 2,
    isTrap: true,
    tags: ['airbag', 'cinturón', 'complementario', 'seguridad'],
    options: [
      { text: 'Que el airbag sustituye al cinturón en colisiones frontales graves', isCorrect: false },
      { text: 'Que el airbag protege aunque no se lleve el cinturón puesto', isCorrect: false },
      { text: 'Que el airbag solo funciona correctamente junto al cinturón de seguridad', isCorrect: true },
      { text: 'Que se puede ir sin cinturón si el vehículo tiene airbag lateral', isCorrect: false },
    ],
  },

  // ─── ROAD_USE (Uso de la Vía) ─────────────────────────────────────────────

  {
    prompt: 'En autopista con condiciones normales, ¿cuál es la velocidad mínima genérica para turismos?',
    explanation: 'En autopistas y autovías con dos o más carriles, la velocidad mínima es el 50% de la velocidad máxima: 60 km/h cuando el límite es 120 km/h. Circular por debajo supone una infracción y puede crear peligro al provocar alcances.',
    category: 'ROAD_USE',
    difficulty: 2,
    isTrap: false,
    tags: ['velocidad mínima', 'autopista', '60 km/h'],
    options: [
      { text: '80 km/h', isCorrect: false },
      { text: '50 km/h', isCorrect: false },
      { text: '60 km/h', isCorrect: true },
      { text: 'No existe velocidad mínima en autopista', isCorrect: false },
    ],
  },
  {
    prompt: '¿Para qué está destinado el carril VAO en las autopistas?',
    explanation: 'El carril VAO (Vehículos de Alta Ocupación) es un carril reservado para vehículos que transporten un número mínimo de ocupantes (normalmente 2 o más). Su objetivo es incentivar el uso compartido del vehículo y reducir la congestión.',
    category: 'ROAD_USE',
    difficulty: 1,
    isTrap: false,
    tags: ['VAO', 'alta ocupación', 'autopista', 'carril'],
    options: [
      { text: 'Vehículos de emergencia y policía', isCorrect: false },
      { text: 'Vehículos con alta potencia (más de 300 CV)', isCorrect: false },
      { text: 'Vehículos con un número mínimo de ocupantes (alta ocupación)', isCorrect: true },
      { text: 'Autobuses y vehículos de transporte público únicamente', isCorrect: false },
    ],
  },
  {
    prompt: '¿Puede un conductor circular continuamente por el carril izquierdo de una autopista si su velocidad es la máxima permitida?',
    explanation: 'No. En autopistas y autovías, el carril izquierdo está reservado exclusivamente para adelantar. Aunque se circule a la velocidad máxima, no se puede ocupar permanentemente el carril izquierdo. Una vez finalizado el adelantamiento, es obligatorio volver al carril de la derecha.',
    category: 'ROAD_USE',
    difficulty: 2,
    isTrap: true,
    tags: ['carril izquierdo', 'autopista', 'adelantar', 'obligación'],
    options: [
      { text: 'Sí, si circula a 120 km/h y no entorpece a nadie', isCorrect: false },
      { text: 'Sí, si hay mucho tráfico en el carril derecho', isCorrect: false },
      { text: 'No, el carril izquierdo es solo para adelantar, luego hay que volver a la derecha', isCorrect: true },
      { text: 'Solo en autopistas de 3 carriles puede usar el central permanentemente', isCorrect: false },
    ],
  },
  {
    prompt: 'Una línea longitudinal continua en el centro de la calzada, ¿qué prohibe?',
    explanation: 'La línea continua en el eje de la calzada prohíbe cruzarla o invadirla, aunque sea parcialmente. No se puede adelantar, girar o maniobrar cruzando esta línea. Solo puede rebasarse en situaciones de extrema necesidad y de forma transitoria cuando no haya peligro.',
    category: 'ROAD_USE',
    difficulty: 1,
    isTrap: false,
    tags: ['línea continua', 'prohibición', 'cruzar', 'calzada'],
    options: [
      { text: 'Aparcar en el lado izquierdo de la vía', isCorrect: false },
      { text: 'Cruzarla o invadirla para adelantar o girar', isCorrect: true },
      { text: 'Circular por encima de ella a más de 90 km/h', isCorrect: false },
      { text: 'Detenerse junto a ella en caso de emergencia', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué indica una marca vial de color amarillo pintada sobre el pavimento?',
    explanation: 'Las marcas amarillas son señalizaciones temporales y tienen prioridad sobre las blancas. Se usan principalmente en obras, eventos o situaciones provisionales para modificar la ordenación del tráfico. Cuando existan marcas amarillas y blancas, hay que obedecer las amarillas.',
    category: 'ROAD_USE',
    difficulty: 2,
    isTrap: false,
    tags: ['marcas amarillas', 'temporales', 'obras', 'prioridad'],
    options: [
      { text: 'Que la vía está reservada para bicicletas', isCorrect: false },
      { text: 'Que es una marca de señalización permanente de aparcamiento', isCorrect: false },
      { text: 'Que es una señalización temporal (obras u ordenación provisional)', isCorrect: true },
      { text: 'Que la vía tiene preferencia frente a vías secundarias', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué es un carril reversible y cómo sabe el conductor si puede usarlo?',
    explanation: 'Un carril reversible es aquel que puede ser usado en ambos sentidos de circulación según el momento del día o la densidad de tráfico. El conductor debe guiarse por las señales variables situadas sobre él (semáforos de carril o paneles de mensaje variable): flecha verde = circulación permitida; X roja = prohibida la circulación.',
    category: 'ROAD_USE',
    difficulty: 2,
    isTrap: false,
    tags: ['carril reversible', 'señales variables', 'semáforo carril'],
    options: [
      { text: 'Mirando si hay tráfico en sentido contrario antes de entrar', isCorrect: false },
      { text: 'Observando las señales variables sobre el carril (flecha verde o X roja)', isCorrect: true },
      { text: 'El carril reversible siempre está marcado con líneas amarillas continuas', isCorrect: false },
      { text: 'Si la hora es punta de mañana, siempre se puede usar el carril extra', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuál es la regla de los "2 segundos" para la distancia de seguridad?',
    explanation: 'La regla de los 2 segundos consiste en tomar un punto fijo de la vía (una señal, un árbol) y contar 2 segundos desde que el vehículo delantero lo sobrepasa hasta que el tuyo llega a ese punto. Si tardas menos de 2 segundos, vas demasiado cerca. En condiciones adversas (lluvia, niebla) se duplica a 4 segundos.',
    category: 'ROAD_USE',
    difficulty: 2,
    isTrap: false,
    tags: ['distancia seguridad', '2 segundos', 'seguimiento'],
    options: [
      { text: 'Mantener una distancia de 2 metros por cada 10 km/h de velocidad', isCorrect: false },
      { text: 'Contar 2 segundos entre que el vehículo delantero pasa un punto y tu vehículo llega a él', isCorrect: true },
      { text: 'Dejar siempre un espacio de al menos 50 metros independientemente de la velocidad', isCorrect: false },
      { text: 'Que el conductor pueda ver las ruedas del vehículo delantero desde el asiento', isCorrect: false },
    ],
  },
  {
    prompt: 'En una vía de 30 km/h junto a un colegio, ¿qué velocidad máxima debes respetar en el horario escolar?',
    explanation: 'Las zonas escolares, hospitales y similares tienen limitaciones específicas de velocidad. Las vías junto a centros escolares y sanitarios están limitadas a 30 km/h. Esta restricción se aplica especialmente en horario escolar/sanitario, aunque la señalización permanente obliga en todo momento si no hay señal horaria.',
    category: 'ROAD_USE',
    difficulty: 1,
    isTrap: false,
    tags: ['zona escolar', 'hospital', '30 km/h', 'restricción'],
    options: [
      { text: '20 km/h en horario escolar', isCorrect: false },
      { text: '50 km/h, igual que el resto de la zona urbana', isCorrect: false },
      { text: '30 km/h según señalización', isCorrect: true },
      { text: '40 km/h si hay agente regulando el tráfico', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué significa la señal de "ceda el paso" (triángulo invertido) para el conductor que la ve?',
    explanation: 'La señal de "ceda el paso" obliga al conductor a reducir la velocidad hasta detenerse si es necesario, y a ceder el paso a los vehículos que circulan por la vía a la que se accede. No impone una parada obligatoria, pero sí la cesión de prioridad.',
    category: 'ROAD_USE',
    difficulty: 1,
    isTrap: false,
    tags: ['ceda el paso', 'prioridad', 'intersección'],
    options: [
      { text: 'Parar completamente e incorporarse solo si la vía está libre', isCorrect: false },
      { text: 'Reducir velocidad y ceder el paso a los vehículos con preferencia', isCorrect: true },
      { text: 'Solo ceder el paso si hay vehículos visibles a la izquierda', isCorrect: false },
      { text: 'Incorporarse a la vía manteniendo la velocidad para no entorpecer el tráfico', isCorrect: false },
    ],
  },
  {
    prompt: 'En una autopista, un vehículo averiado debe detenerse en el arcén. ¿Por qué no debe permanecer en el carril de circulación?',
    explanation: 'Permanecer en el carril de circulación con el vehículo averiado supone un riesgo extremo de alcance, especialmente en autopista. El arcén es la zona habilitada para emergencias. Si no se puede llegar al arcén, deben encenderse los hazards y colocar los triángulos lo antes posible para avisar al resto del tráfico.',
    category: 'ROAD_USE',
    difficulty: 1,
    isTrap: false,
    tags: ['avería', 'arcén', 'autopista', 'emergencia'],
    options: [
      { text: 'Porque el arcén está reservado exclusivamente para vehículos de emergencia', isCorrect: false },
      { text: 'Para evitar el riesgo de alcance y no obstruir el tráfico', isCorrect: true },
      { text: 'Porque la normativa prohíbe detenerse en el carril solo en autovías', isCorrect: false },
      { text: 'Porque el arcén tiene superficie antiderrapante especial para vehículos averiados', isCorrect: false },
    ],
  },
  {
    prompt: 'En un carril bici señalizado, ¿puede circular un ciclomotor si el conductor no quiere entorpecer el tráfico motorizado?',
    explanation: 'No. El carril bici está reservado exclusivamente para bicicletas y, en algunos casos, para VMP (patinetes eléctricos) cuando así se señalice. Los ciclomotores deben circular por la calzada como el resto de vehículos de motor. Circular por el carril bici con un ciclomotor es una infracción.',
    category: 'ROAD_USE',
    difficulty: 2,
    isTrap: true,
    tags: ['carril bici', 'ciclomotor', 'prohibición'],
    options: [
      { text: 'Sí, si circula a menos de 25 km/h', isCorrect: false },
      { text: 'Sí, si no hay bicicletas en ese momento', isCorrect: false },
      { text: 'No, el carril bici está reservado solo para bicicletas y VMP autorizados', isCorrect: true },
      { text: 'Sí, en zonas escolares o residenciales de 30 km/h', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué indica en autopista una señal de panel variable con una "X" roja sobre un carril?',
    explanation: 'Una "X" roja sobre un carril en un panel variable de autopista indica que ese carril está CERRADO al tráfico. Puede deberse a un accidente, obras, un vehículo averiado o una emergencia. Continuar circulando por ese carril es una infracción muy grave.',
    category: 'ROAD_USE',
    difficulty: 2,
    isTrap: false,
    tags: ['panel variable', 'X roja', 'carril cerrado', 'autopista'],
    options: [
      { text: 'Que el carril tiene límite de velocidad de 60 km/h', isCorrect: false },
      { text: 'Que el carril está en obras y hay que extremar precauciones', isCorrect: false },
      { text: 'Que el carril está cerrado y no se puede circular por él', isCorrect: true },
      { text: 'Que el carril tiene preferencia para vehículos de emergencia', isCorrect: false },
    ],
  },

  // ─── CARGO (Carga y Transporte) ───────────────────────────────────────────

  {
    prompt: '¿Cuándo debe colocarse la señal V-20 en un vehículo?',
    explanation: 'La señal V-20 (panel de señalización de carga) debe colocarse cuando la carga o el dispositivo de transporte sobresale más de 25 cm de las luces traseras o más de 1,5 metros del plano posterior del vehículo. Son bandas diagonales blancas y rojas retrorreflectantes.',
    category: 'CARGO',
    difficulty: 2,
    isTrap: false,
    tags: ['V-20', 'señal carga', 'sobresalencia', '25cm'],
    options: [
      { text: 'Cuando la carga sobresale más de 50 cm del plano trasero', isCorrect: false },
      { text: 'Cuando la carga sobresale más de 25 cm de las luces traseras o más de 1,5 m del plano posterior', isCorrect: true },
      { text: 'Siempre que se transporte cualquier objeto en el exterior del vehículo', isCorrect: false },
      { text: 'Solo cuando la carga sobresale por los laterales', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuál es el requisito fundamental que debe cumplir toda carga transportada en un vehículo?',
    explanation: 'Toda carga debe estar correctamente sujeta y estibada para que no pueda desplazarse, caer o arrastrar durante la circulación. Un cargamento mal sujeto es peligroso para el propio vehículo, para otros usuarios y puede dar lugar a responsabilidades civiles y penales.',
    category: 'CARGO',
    difficulty: 1,
    isTrap: false,
    tags: ['carga', 'sujeción', 'seguridad', 'desplazamiento'],
    options: [
      { text: 'Que no supere la capacidad volumétrica del vehículo', isCorrect: false },
      { text: 'Que esté sujeta para que no se desplace, caiga ni arrastre', isCorrect: true },
      { text: 'Que no supere el 80% del MMA del vehículo', isCorrect: false },
      { text: 'Que esté cubierta por una lona impermeable en todo momento', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuál es la sobresalencia lateral máxima permitida para una carga que sobresale del vehículo?',
    explanation: 'La normativa española permite que la carga sobresalga lateralmente hasta 40 cm por cada lado medidos desde el punto más ancho del vehículo. Si supera esa medida, la carga es ilegal y supone peligro para los usuarios vulnerables (ciclistas, peatones).',
    category: 'CARGO',
    difficulty: 2,
    isTrap: false,
    tags: ['carga', 'lateral', '40cm', 'sobresalencia'],
    options: [
      { text: '25 cm por cada lado', isCorrect: false },
      { text: '50 cm por cada lado', isCorrect: false },
      { text: '40 cm por cada lado', isCorrect: true },
      { text: '30 cm por cada lado', isCorrect: false },
    ],
  },
  {
    prompt: '¿Pueden viajar personas en la zona de carga de un vehículo (caja de un camión o pick-up)?',
    explanation: 'Con carácter general, está prohibido transportar personas en la zona de carga. Solo se permite en casos excepcionales con habilitación especial (por ejemplo, determinados trabajos agrícolas en zonas autorizadas). Nunca está permitido en carretera convencional o autopista.',
    category: 'CARGO',
    difficulty: 2,
    isTrap: false,
    tags: ['carga', 'personas', 'prohibición', 'camión'],
    options: [
      { text: 'Sí, si van sentados y sujetos con asideros', isCorrect: false },
      { text: 'Sí, si el vehículo circula a menos de 40 km/h', isCorrect: false },
      { text: 'No, salvo habilitación especial en casos concretos', isCorrect: true },
      { text: 'Sí, hasta 3 personas en la zona de carga de un pick-up', isCorrect: false },
    ],
  },
  {
    prompt: 'Un remolque no tiene sistema de frenos propio. ¿A qué velocidad máxima puede circular el vehículo que lo remolca?',
    explanation: 'Los remolques sin frenos propios limitan la velocidad del vehículo tractor a un máximo de 30 km/h. Esta restricción existe porque sin frenos en el remolque, la capacidad de detención del conjunto es muy limitada y el riesgo de alcance es elevado.',
    category: 'CARGO',
    difficulty: 2,
    isTrap: false,
    tags: ['remolque', 'sin frenos', '30 km/h', 'velocidad máxima'],
    options: [
      { text: '50 km/h', isCorrect: false },
      { text: '40 km/h', isCorrect: false },
      { text: '30 km/h', isCorrect: true },
      { text: '20 km/h', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué incluye el MMA (Masa Máxima Autorizada) de un vehículo?',
    explanation: 'El MMA o Masa Máxima Autorizada es el peso total máximo con el que puede circular el vehículo legalmente. Incluye la tara del propio vehículo (peso en vacío), la carga que transporta y el peso de todos los ocupantes. Superarlo conlleva una infracción grave.',
    category: 'CARGO',
    difficulty: 2,
    isTrap: false,
    tags: ['MMA', 'masa máxima', 'tara', 'carga', 'ocupantes'],
    options: [
      { text: 'Solo el peso del vehículo vacío más la carga máxima', isCorrect: false },
      { text: 'El peso del vehículo en vacío más el combustible', isCorrect: false },
      { text: 'El peso total: vehículo + carga + ocupantes', isCorrect: true },
      { text: 'El peso de la carga útil sin incluir el peso del vehículo', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué permiso de conducción necesita un conductor con permiso B para enganchar un remolque de 750 kg de MMA?',
    explanation: 'El permiso B autoriza a llevar un remolque cuyo MMA no supere los 750 kg. Si el remolque tiene una MMA de exactamente 750 kg o menos, no se necesita ningún permiso adicional. A partir de 750 kg se necesita el permiso B+E o BE.',
    category: 'CARGO',
    difficulty: 2,
    isTrap: true,
    tags: ['remolque', 'permiso B', '750kg', 'MMA'],
    options: [
      { text: 'Necesita el permiso BE adicional aunque sea solo 750 kg', isCorrect: false },
      { text: 'El permiso B es suficiente para remolques hasta 750 kg de MMA', isCorrect: true },
      { text: 'Necesita el permiso C1 para remolques de más de 500 kg', isCorrect: false },
      { text: 'El permiso B solo permite remolques hasta 500 kg de MMA', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cómo son las bandas de la señal V-20 que se coloca en cargas sobresalientes?',
    explanation: 'La señal V-20 consiste en un panel formado por bandas diagonales alternas de color blanco y rojo, ambas retrorreflectantes para que sean visibles de noche. Se coloca en el extremo posterior de la carga sobresaliente.',
    category: 'CARGO',
    difficulty: 2,
    isTrap: false,
    tags: ['V-20', 'bandas', 'blanco', 'rojo', 'retrorreflectante'],
    options: [
      { text: 'Bandas horizontales amarillas y negras', isCorrect: false },
      { text: 'Bandas diagonales alternas blancas y rojas retrorreflectantes', isCorrect: true },
      { text: 'Bandas verticales naranjas y blancas', isCorrect: false },
      { text: 'Bandas horizontales rojas continuas sobre fondo blanco', isCorrect: false },
    ],
  },
  {
    prompt: 'Una furgoneta de reparto carga cajas hasta el techo de la zona de carga. Las cajas impiden ver por el espejo retrovisor interior. ¿Es esto legal?',
    explanation: 'En furgonetas y vehículos comerciales, la visibilidad por el espejo retrovisor interior puede quedar anulada por la carga. Esto es legalmente aceptable siempre que el vehículo disponga de espejos exteriores en ambos lados que garanticen la visibilidad hacia atrás. El retrovisor interior no es obligatorio en vehículos comerciales con carga.',
    category: 'CARGO',
    difficulty: 3,
    isTrap: true,
    tags: ['furgoneta', 'carga', 'retrovisor', 'visibilidad'],
    options: [
      { text: 'No, siempre debe ser visible la calzada posterior desde el interior', isCorrect: false },
      { text: 'No, la carga nunca puede superar la altura de los asientos delanteros', isCorrect: false },
      { text: 'Sí, si dispone de espejos exteriores en ambos lados que garanticen la visibilidad trasera', isCorrect: true },
      { text: 'Solo es legal si el vehículo dispone de cámara de marcha atrás', isCorrect: false },
    ],
  },
  {
    prompt: 'Una bicicleta transportada en el portabicicletas trasero de un turismo sobresale de las luces traseras. ¿Qué señalización adicional es obligatoria?',
    explanation: 'Cuando una bicicleta o cualquier elemento en el portabicicletas cubre o supera las luces traseras del vehículo, es obligatorio instalar en la bicicleta (o el soporte) una luz trasera roja y un reflectante rojo visibles desde atrás. Además, si sobresale más de 25 cm, hay que colocar la señal V-20.',
    category: 'CARGO',
    difficulty: 2,
    isTrap: false,
    tags: ['portabicicletas', 'luces traseras', 'V-20', 'señalización'],
    options: [
      { text: 'Nada especial, el portabicicletas es un accesorio homologado', isCorrect: false },
      { text: 'Solo usar las luces de emergencia mientras circula', isCorrect: false },
      { text: 'Luz trasera roja y reflectante en la bicicleta, y señal V-20 si sobresale más de 25 cm', isCorrect: true },
      { text: 'Luz trasera verde en la bicicleta para diferenciarla del vehículo', isCorrect: false },
    ],
  },

  // ─── RISK_FACTORS (Factores de Riesgo) ────────────────────────────────────

  {
    prompt: 'Usas el móvil sujetado en mano mientras esperas en un semáforo en rojo. ¿Qué sanción conlleva?',
    explanation: 'El uso del teléfono móvil sujetado en mano está prohibido siempre que el vehículo esté en la vía, incluyendo paradas en semáforos. La sanción es de 200 euros de multa y la pérdida de 6 puntos del carné de conducir.',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: true,
    tags: ['móvil', 'semáforo', 'sanción', 'puntos'],
    options: [
      { text: 'Ninguna, el vehículo está detenido y no circula', isCorrect: false },
      { text: '100 euros y 3 puntos, porque el motor no está en movimiento', isCorrect: false },
      { text: '200 euros de multa y pérdida de 6 puntos del carné', isCorrect: true },
      { text: '200 euros solo si hay un agente presente', isCorrect: false },
    ],
  },
  {
    prompt: '¿A qué estado equivale conducir tras 17-18 horas sin dormir, según estudios de seguridad vial?',
    explanation: 'Investigaciones científicas citadas por la DGT y la Agencia Europea de Seguridad Vial demuestran que conducir tras 17-18 horas sin dormir produce un deterioro de los reflejos y la capacidad de atención equivalente a conducir con una tasa de alcohol de 0,5 g/l en sangre (el límite legal general en España).',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: false,
    tags: ['somnolencia', 'alcohol', 'equivalencia', '0,5 g/l'],
    options: [
      { text: 'Equivale a 0,25 g/l de alcohol en sangre', isCorrect: false },
      { text: 'Equivale a 0,5 g/l de alcohol en sangre', isCorrect: true },
      { text: 'Equivale a 1,2 g/l de alcohol en sangre', isCorrect: false },
      { text: 'No tiene equivalencia demostrada con el alcohol', isCorrect: false },
    ],
  },
  {
    prompt: '¿Con qué frecuencia mínima recomienda la DGT hacer paradas en viajes de larga duración?',
    explanation: 'La DGT recomienda parar y descansar al menos 15-20 minutos cada 2 horas de conducción continuada. Las paradas frecuentes previenen la fatiga y la somnolencia, que son factores de riesgo en los desplazamientos de larga distancia.',
    category: 'RISK_FACTORS',
    difficulty: 1,
    isTrap: false,
    tags: ['viaje largo', 'parada', '2 horas', 'fatiga'],
    options: [
      { text: 'Cada 4 horas de conducción', isCorrect: false },
      { text: 'Cada 3 horas de conducción', isCorrect: false },
      { text: 'Cada 2 horas de conducción', isCorrect: true },
      { text: 'Solo cuando el conductor sienta cansancio', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cómo afecta el estrés a la conducción?',
    explanation: 'El estrés reduce la capacidad de atención y concentración del conductor, estrecha el campo visual y aumenta la agresividad al volante. Además, provoca mayor impulsividad en la toma de decisiones y menor tolerancia hacia otros conductores, incrementando el riesgo de infracciones y accidentes.',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: false,
    tags: ['estrés', 'concentración', 'agresividad', 'conducción'],
    options: [
      { text: 'Aumenta el estado de alerta, mejorando los reflejos del conductor', isCorrect: false },
      { text: 'Reduce la concentración y aumenta la agresividad al volante', isCorrect: true },
      { text: 'No influye en la conducción si el conductor tiene experiencia', isCorrect: false },
      { text: 'Solo afecta en trayectos urbanos con mucho tráfico', isCorrect: false },
    ],
  },
  {
    prompt: 'Un medicamento lleva en el envase un triángulo negro invertido. ¿Qué precaución debe tomar el conductor?',
    explanation: 'El triángulo negro invertido en el envase de un medicamento indica que está sujeto a monitorización adicional por parte de las autoridades sanitarias. Muchos de estos fármacos pueden afectar a la capacidad de conducción. El conductor debe consultar al médico o farmacéutico y leer el prospecto, ya que algunos de estos medicamentos están contraindicados para conducir.',
    category: 'RISK_FACTORS',
    difficulty: 3,
    isTrap: false,
    tags: ['medicamentos', 'triángulo negro', 'conducción', 'prospecto'],
    options: [
      { text: 'No hay ninguna restricción especial para conductores', isCorrect: false },
      { text: 'Puede tomarlo con total seguridad si no siente somnolencia', isCorrect: false },
      { text: 'Debe consultar al médico o farmacéutico ya que puede afectar a la conducción', isCorrect: true },
      { text: 'Está completamente prohibido conducir si toma ese medicamento', isCorrect: false },
    ],
  },
  {
    prompt: 'Circulando a 90 km/h, te distrae leer un mensaje de texto 2 segundos. ¿Cuántos metros recorres a ciegas aproximadamente?',
    explanation: 'A 90 km/h se recorren 25 metros por segundo. En 2 segundos de distracción el vehículo avanza 50 metros sin que el conductor mire la vía. En ese espacio puede aparecer un obstáculo, un cruce o un peatón sin que el conductor lo detecte.',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: false,
    tags: ['móvil', 'distracción', '50 metros', '90 km/h', 'texto'],
    options: [
      { text: 'Unos 25 metros', isCorrect: false },
      { text: 'Unos 50 metros', isCorrect: true },
      { text: 'Unos 100 metros', isCorrect: false },
      { text: 'Unos 15 metros', isCorrect: false },
    ],
  },
  {
    prompt: '¿Por qué el consumo de drogas estimulantes (cocaína, anfetaminas) es peligroso al volante aunque el conductor se sienta más alerta?',
    explanation: 'Las drogas estimulantes generan una falsa sensación de alerta y competencia. En realidad, alteran la percepción del riesgo, aumentan la impulsividad, deterioran la visión periférica y la coordinación motora, y producen sobreconfianza. Además, cuando el efecto cesa aparece un bajón brusco de alerta que puede provocar un accidente.',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: false,
    tags: ['drogas', 'estimulantes', 'falsa alerta', 'riesgo'],
    options: [
      { text: 'Porque aumentan el tiempo de reacción de forma proporcional a la dosis', isCorrect: false },
      { text: 'Porque generan sobreconfianza y alteran la percepción del riesgo', isCorrect: true },
      { text: 'Porque producen somnolencia inmediata en condiciones de calor', isCorrect: false },
      { text: 'Porque reducen la frecuencia cardíaca y disminuyen la atención', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuándo está prohibido fumar al volante en España?',
    explanation: 'Está prohibido fumar al volante cuando haya menores de 18 años en el vehículo, en virtud de la Ley 28/2005 de medidas sanitarias. Independientemente de la presencia de menores, fumar al volante es una distracción y puede sancionarse si afecta a la conducción segura.',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: true,
    tags: ['fumar', 'menores', 'prohibición', 'distracción'],
    options: [
      { text: 'Nunca; está prohibido fumar en todos los vehículos en España', isCorrect: false },
      { text: 'Solo en autopistas de peaje', isCorrect: false },
      { text: 'Cuando haya menores de 18 años en el vehículo', isCorrect: true },
      { text: 'Solo en vehículos de transporte público', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué efecto tienen las enfermedades febriles en la capacidad de conducción?',
    explanation: 'La fiebre provoca reducción de la atención y la concentración, enlentecimiento de los reflejos, sensaciones distorsionadas, mareos y, en ocasiones, estados confusionales. Conducir con fiebre incrementa significativamente el riesgo de accidente y está desaconsejado salvo emergencia.',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: false,
    tags: ['fiebre', 'enfermedad', 'reflejos', 'conducción'],
    options: [
      { text: 'Aumentan el estado de vigilia porque el organismo está activado', isCorrect: false },
      { text: 'Solo afectan si la fiebre supera los 39 ºC', isCorrect: false },
      { text: 'Reducen los reflejos, la concentración y pueden causar mareos', isCorrect: true },
      { text: 'No afectan si el conductor toma analgésicos antes de salir', isCorrect: false },
    ],
  },
  {
    prompt: 'Llevas horas conduciendo en autopista y sientes somnolencia. ¿Cuál es la ÚNICA solución eficaz?',
    explanation: 'La única solución real y eficaz contra la somnolencia al volante es parar y dormir. Tomar café, abrir la ventanilla o poner la radio alta son medidas que pueden retrasar la somnolencia unos minutos pero no la eliminan. La DGT insiste en que solo el descanso real resuelve el problema.',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: true,
    tags: ['somnolencia', 'descanso', 'café', 'autopista'],
    options: [
      { text: 'Tomar un café y abrir la ventanilla para recibir aire fresco', isCorrect: false },
      { text: 'Poner la radio a alto volumen para mantener la atención', isCorrect: false },
      { text: 'Parar en lugar seguro y descansar o dormir', isCorrect: true },
      { text: 'Reducir la velocidad a 80 km/h y continuar con precaución', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué es la "fatiga de autopista" y qué la provoca?',
    explanation: 'La fatiga de autopista es un tipo de somnolencia causada por la monotonía del paisaje, la vibración del vehículo y la ausencia de estímulos variados que caracteriza a las vías de alta capacidad. A diferencia de la fatiga general, puede aparecer de forma brusca sin señales previas claras, por lo que es especialmente peligrosa.',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: false,
    tags: ['fatiga autopista', 'monotonía', 'vibración', 'somnolencia'],
    options: [
      { text: 'El cansancio producido por circular a alta velocidad durante mucho tiempo', isCorrect: false },
      { text: 'Somnolencia causada por la monotonía y vibración en vías sin estímulos variados', isCorrect: true },
      { text: 'La fatiga muscular del conductor por mantener el volante en posición fija', isCorrect: false },
      { text: 'Un efecto visual producido por las líneas discontinuas en autopista', isCorrect: false },
    ],
  },
  {
    prompt: 'Leer y enviar mensajes de texto mientras se conduce es una distracción triple. ¿Por qué?',
    explanation: 'Textear al volante combina tres tipos de distracción: visual (los ojos no están en la vía), manual (una o ambas manos no están en el volante) y cognitiva (la mente está centrada en el mensaje, no en la conducción). Esta combinación lo convierte en una de las distracciones más peligrosas posibles.',
    category: 'RISK_FACTORS',
    difficulty: 2,
    isTrap: false,
    tags: ['texto', 'distracción', 'visual', 'manual', 'cognitiva'],
    options: [
      { text: 'Porque requiere leer, escribir y pulsar enviar: tres acciones físicas', isCorrect: false },
      { text: 'Porque es distracción visual, manual y cognitiva simultáneamente', isCorrect: true },
      { text: 'Porque el teléfono emite radiaciones que interfieren con el sistema de luces', isCorrect: false },
      { text: 'Porque provoca fatiga visual al mirar la pantalla pequeña del móvil', isCorrect: false },
    ],
  },

  // ─── VULNERABLE_USERS (Usuarios Vulnerables) ─────────────────────────────

  {
    prompt: 'Un peatón está cruzando por un paso de cebra. ¿Qué preferencia tiene frente a los vehículos?',
    explanation: 'Los peatones que están cruzando o van a cruzar por un paso de peatones señalizado tienen preferencia absoluta sobre los vehículos. El conductor debe ceder el paso aunque el peatón no haya puesto aún el pie en el paso, si está claramente esperando para cruzar.',
    category: 'VULNERABLE_USERS',
    difficulty: 1,
    isTrap: false,
    tags: ['peatón', 'paso de cebra', 'preferencia', 'ceder'],
    options: [
      { text: 'Preferencia solo si ya está en el paso', isCorrect: false },
      { text: 'Preferencia absoluta, incluso si aún no ha puesto el pie en el paso', isCorrect: true },
      { text: 'Preferencia únicamente si hay señal de STOP en la calzada', isCorrect: false },
      { text: 'Solo de noche; de día los vehículos tienen prioridad si circulan en verde', isCorrect: false },
    ],
  },
  {
    prompt: 'Vas a adelantar a un ciclista en una carretera convencional con línea continua. ¿Puedes hacerlo?',
    explanation: 'Sí. La normativa española permite rebasar la línea continua para adelantar a ciclistas en carreteras convencionales si se puede hacer con seguridad, manteniendo una distancia lateral mínima de 1,5 metros. Es una excepción específica prevista en el Reglamento de Circulación para proteger a los ciclistas.',
    category: 'VULNERABLE_USERS',
    difficulty: 3,
    isTrap: true,
    tags: ['ciclista', 'adelantar', 'línea continua', '1,5 metros'],
    options: [
      { text: 'No, la línea continua no puede cruzarse en ningún caso', isCorrect: false },
      { text: 'Sí, si se mantiene una distancia lateral mínima de 1,5 metros', isCorrect: true },
      { text: 'Solo si hay visibilidad suficiente y la velocidad es menor de 50 km/h', isCorrect: false },
      { text: 'Solo si no hay vehículos en sentido contrario a más de 200 metros', isCorrect: false },
    ],
  },
  {
    prompt: '¿Por qué vía puede circular un VMP (patinete eléctrico) legalmente?',
    explanation: 'Los VMP (Vehículos de Movilidad Personal) como los patinetes eléctricos homologados solo pueden circular por carriles bici, vías ciclistas o calzadas con límite de 30 km/h o menos. Están terminantemente prohibidos en aceras, zonas peatonales y calzadas de más de 30 km/h. Su velocidad máxima es 25 km/h.',
    category: 'VULNERABLE_USERS',
    difficulty: 2,
    isTrap: false,
    tags: ['VMP', 'patinete', 'carril bici', '30 km/h', 'acera'],
    options: [
      { text: 'Por aceras amplias si circula a menos de 10 km/h', isCorrect: false },
      { text: 'Por cualquier vía urbana si cede el paso a los peatones', isCorrect: false },
      { text: 'Por carriles bici o calzadas con límite de 30 km/h o menos; nunca por aceras', isCorrect: true },
      { text: 'Por el arcén de las carreteras interurbanas a menos de 25 km/h', isCorrect: false },
    ],
  },
  {
    prompt: 'Al acercarte a un grupo de personas mayores cruzando la calle fuera del paso de peatones, ¿qué debes hacer?',
    explanation: 'Aunque los peatones que cruzan fuera del paso de peatones no tienen preferencia formal, el conductor debe extremar las precauciones con personas mayores, personas con discapacidad y niños, reduciendo la velocidad y estando preparado para detenerse. La normativa exige especial atención ante estos usuarios vulnerables.',
    category: 'VULNERABLE_USERS',
    difficulty: 2,
    isTrap: false,
    tags: ['personas mayores', 'vulnerables', 'precaución', 'peatones'],
    options: [
      { text: 'Mantener la velocidad, ellos no tienen preferencia fuera del paso', isCorrect: false },
      { text: 'Tocar el claxon para advertirles de que van a cruzar', isCorrect: false },
      { text: 'Reducir la velocidad y estar preparado para detenerse; extremar precauciones', isCorrect: true },
      { text: 'Continuar con precaución si hay agente que regule el tráfico', isCorrect: false },
    ],
  },
  {
    prompt: 'Un grupo de más de 15 ciclistas circula en columna por una carretera. ¿Pueden ir en doble fila?',
    explanation: 'Los grupos de más de 15 ciclistas en columna pueden circular en doble fila, siempre y cuando no supongan un peligro para el resto del tráfico y cuenten con la señalización adecuada. Es una excepción específica del Reglamento para pelotas o grupos ciclistas numerosos.',
    category: 'VULNERABLE_USERS',
    difficulty: 3,
    isTrap: false,
    tags: ['grupo ciclistas', 'doble fila', 'columna', '>15'],
    options: [
      { text: 'No, los ciclistas siempre deben circular en fila de uno', isCorrect: false },
      { text: 'Solo si tienen escolta policial', isCorrect: false },
      { text: 'Sí, grupos de más de 15 ciclistas pueden circular en doble fila', isCorrect: true },
      { text: 'Solo en zonas 30 o ciclovías específicas', isCorrect: false },
    ],
  },
  {
    prompt: 'En una zona 30 km/h con un solo carril por sentido, ¿qué usuarios tienen especial presencia y derechos?',
    explanation: 'Las zonas 30 se diseñan para calles con un único carril por sentido y priorizan la convivencia entre vehículos, ciclistas y peatones. En estas zonas se facilita que ciclistas y peatones tengan mayor protagonismo y seguridad. Los vehículos deben ceder el paso a los ciclistas que salen de los carriles bici.',
    category: 'VULNERABLE_USERS',
    difficulty: 2,
    isTrap: false,
    tags: ['zona 30', 'ciclistas', 'peatones', 'prioridad'],
    options: [
      { text: 'Los vehículos pesados tienen preferencia para facilitar la entrega de mercancías', isCorrect: false },
      { text: 'Los ciclistas y peatones tienen mayor protagonismo y seguridad que en zonas de 50', isCorrect: true },
      { text: 'Solo los peatones, los ciclistas deben usar el carril bici si hay uno', isCorrect: false },
      { text: 'Nadie tiene preferencia especial; rigen las normas generales', isCorrect: false },
    ],
  },
  {
    prompt: '¿Por qué los ciclistas y las motos pueden quedar en el ángulo muerto (punto ciego) de un camión?',
    explanation: 'Los camiones tienen grandes ángulos muertos (zonas no visibles en los espejos) especialmente por los lados derecho e izquierdo trasero y la parte frontal. Un ciclista o moto situados en estas zonas son completamente invisibles para el conductor del camión. Por ello, los usuarios vulnerables deben evitar circular junto a un camión, especialmente en cruces o giros.',
    category: 'VULNERABLE_USERS',
    difficulty: 2,
    isTrap: false,
    tags: ['ángulo muerto', 'camión', 'ciclista', 'moto', 'punto ciego'],
    options: [
      { text: 'Porque los camiones tienen retrovisores de menor calidad que los turismos', isCorrect: false },
      { text: 'Porque los camiones tienen grandes zonas no cubiertas por ningún espejo', isCorrect: true },
      { text: 'Solo ocurre de noche cuando el conductor del camión lleva mucho tiempo conduciendo', isCorrect: false },
      { text: 'Solo afecta a ciclistas, las motos siempre son visibles por su mayor altura', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué debe hacer un conductor al acercarse a un autobús escolar con la señal de parada activa (señal STOP desplegada)?',
    explanation: 'Cuando un autobús escolar tiene activa la señal de parada (señal STOP de color rojo desplegada lateralmente), todos los vehículos deben detener su marcha en ambos sentidos de la calzada. No se puede adelantar ni rebasar el autobús hasta que la señal se retire.',
    category: 'VULNERABLE_USERS',
    difficulty: 2,
    isTrap: false,
    tags: ['autobús escolar', 'señal STOP', 'parada', 'detener'],
    options: [
      { text: 'Reducir la velocidad a 20 km/h y pasar con precaución', isCorrect: false },
      { text: 'Parar el vehículo hasta que se retire la señal de STOP del autobús', isCorrect: true },
      { text: 'Solo deben parar los vehículos que vienen detrás del autobús', isCorrect: false },
      { text: 'Detener el vehículo y esperar que los niños suban; luego se puede pasar', isCorrect: false },
    ],
  },
  {
    prompt: '¿Por dónde deben circular los peatones en una carretera interurbana de noche y qué deben llevar?',
    explanation: 'Los peatones que circulan por una vía interurbana fuera del poblado deben hacerlo por el lado izquierdo de la calzada (mirando de frente al tráfico que se aproxima) y es obligatorio el uso de chaleco reflectante o elemento reflectante para ser visibles a distancia suficiente.',
    category: 'VULNERABLE_USERS',
    difficulty: 2,
    isTrap: false,
    tags: ['peatón', 'carretera', 'noche', 'izquierda', 'chaleco reflectante'],
    options: [
      { text: 'Por el lado derecho, en el mismo sentido que los vehículos', isCorrect: false },
      { text: 'Por el centro de la calzada para ser visibles desde ambos sentidos', isCorrect: false },
      { text: 'Por el lado izquierdo mirando el tráfico, con chaleco reflectante', isCorrect: true },
      { text: 'Solo por el arcén; si no hay arcén no pueden circular', isCorrect: false },
    ],
  },
  {
    prompt: 'Sales marcha atrás de un garaje privado hacia la acera. ¿Quién tiene preferencia?',
    explanation: 'Los peatones que transitan por la acera tienen preferencia absoluta sobre los vehículos que salen de garajes, aparcamientos o vías privadas. El conductor que sale del garaje debe asegurarse de que no hay peatones antes de ocupar la acera, deteniéndose si es necesario.',
    category: 'VULNERABLE_USERS',
    difficulty: 1,
    isTrap: false,
    tags: ['garaje', 'acera', 'peatón', 'preferencia', 'marcha atrás'],
    options: [
      { text: 'El vehículo, porque ya está en movimiento', isCorrect: false },
      { text: 'El peatón, que tiene preferencia absoluta en la acera', isCorrect: true },
      { text: 'Depende de si hay señalización específica en la salida del garaje', isCorrect: false },
      { text: 'El vehículo si acciona el claxon para avisar al peatón', isCorrect: false },
    ],
  },
  {
    prompt: 'Un ciclista circula por el centro del carril en una carretera de un solo carril por sentido. ¿Está actuando correctamente?',
    explanation: 'Sí. La DGT permite a los ciclistas ocupar el centro del carril cuando es necesario para su seguridad (carreteras estrechas, curvas, pavimento deteriorado en los bordes). El conductor que viene detrás no puede obligarle a circular por el borde y debe esperar para adelantar con 1,5 m de separación.',
    category: 'VULNERABLE_USERS',
    difficulty: 3,
    isTrap: true,
    tags: ['ciclista', 'centro carril', 'seguridad', 'normativa'],
    options: [
      { text: 'No, los ciclistas siempre deben ir pegados al borde derecho de la calzada', isCorrect: false },
      { text: 'No, solo pueden hacerlo si hay carril bici pintado en el centro', isCorrect: false },
      { text: 'Sí, cuando sea necesario para su seguridad puede ocupar el centro del carril', isCorrect: true },
      { text: 'Solo si circula en grupo de más de tres ciclistas', isCorrect: false },
    ],
  },
  {
    prompt: 'Un conductor ve a una persona en silla de ruedas cruzando la calle sin paso habilitado. ¿Qué debe hacer?',
    explanation: 'Las personas con discapacidad, incluyendo las que usan silla de ruedas, son usuarios especialmente vulnerables. El conductor debe reducir la velocidad y ceder el paso, independientemente de si hay o no paso de peatones señalizado, extremando la precaución.',
    category: 'VULNERABLE_USERS',
    difficulty: 2,
    isTrap: false,
    tags: ['discapacidad', 'silla de ruedas', 'vulnerable', 'ceder paso'],
    options: [
      { text: 'Tocar el claxon para alertarle y continuar, ya que no hay paso habilitado', isCorrect: false },
      { text: 'Mantener la velocidad; el peatón no tiene preferencia fuera del paso', isCorrect: false },
      { text: 'Reducir la velocidad y ceder el paso, extremando la precaución', isCorrect: true },
      { text: 'Solo ceder el paso si el agente de tráfico así lo indica', isCorrect: false },
    ],
  },

  // ─── ADVERSE_CONDITIONS (Condiciones Adversas) ───────────────────────────

  {
    prompt: 'Estás circulando a 100 km/h y el vehículo comienza a aquaplanar. ¿Cuál es la reacción correcta?',
    explanation: 'En caso de aquaplaning, el vehículo pierde contacto entre los neumáticos y el asfalto por la película de agua. La reacción correcta es soltar el acelerador suavemente para reducir la velocidad, sin frenar bruscamente ni girar el volante, hasta que los neumáticos vuelvan a tener adherencia.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 2,
    isTrap: true,
    tags: ['aquaplaning', 'lluvia', 'frenada', 'reacción'],
    options: [
      { text: 'Frenar con fuerza para reducir la velocidad lo antes posible', isCorrect: false },
      { text: 'Girar el volante hacia el lado contrario para recuperar la trayectoria', isCorrect: false },
      { text: 'Soltar el acelerador suavemente y no frenar ni girar hasta recuperar adherencia', isCorrect: true },
      { text: 'Acelerar brevemente para superar la zona con agua', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuál es la velocidad máxima permitida al circular con cadenas de nieve en España?',
    explanation: 'Cuando se circula con cadenas de nieve instaladas, la velocidad máxima está limitada a 50 km/h, independientemente del límite genérico de la vía. Superar esa velocidad puede dañar las cadenas y la calzada, y pone en riesgo la seguridad.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 2,
    isTrap: false,
    tags: ['cadenas', 'nieve', '50 km/h', 'velocidad máxima'],
    options: [
      { text: '30 km/h', isCorrect: false },
      { text: '70 km/h', isCorrect: false },
      { text: '50 km/h', isCorrect: true },
      { text: '40 km/h', isCorrect: false },
    ],
  },
  {
    prompt: 'Hay niebla densa y visibilidad muy reducida. ¿Cuál es el principio básico para adaptar la velocidad?',
    explanation: 'Con niebla densa, el conductor debe reducir la velocidad hasta poder detenerse dentro de su campo de visión. Si puede ver 30 metros, debe poder parar en menos de 30 metros. Este principio garantiza que, si hay un obstáculo al límite de la visibilidad, sea posible detener el vehículo antes de colisionar.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 2,
    isTrap: false,
    tags: ['niebla', 'velocidad', 'campo de visión', 'detención'],
    options: [
      { text: 'Circular siempre a 50 km/h como mínimo para no obstruir el tráfico', isCorrect: false },
      { text: 'Reducir la velocidad hasta poder detenerse dentro del campo de visión', isCorrect: true },
      { text: 'Circular a la misma velocidad pero aumentando la distancia de seguridad al doble', isCorrect: false },
      { text: 'Detenerse siempre que la visibilidad sea menor de 200 metros', isCorrect: false },
    ],
  },
  {
    prompt: 'Detectas hielo negro en la calzada. ¿Qué maniobras debes evitar especialmente?',
    explanation: 'El hielo negro (una fina capa de hielo casi transparente sobre el asfalto) hace que la adherencia sea casi nula. Se deben evitar las frenadas bruscas, las aceleraciones bruscas y los giros bruscos del volante. Todo movimiento debe ser suave y progresivo para no perder el control del vehículo.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 2,
    isTrap: false,
    tags: ['hielo negro', 'frenada brusca', 'giro', 'adherencia'],
    options: [
      { text: 'Solo las frenadas bruscas; los giros rápidos son seguros en hielo', isCorrect: false },
      { text: 'Frenadas, aceleraciones y giros bruscos; todo movimiento debe ser suave', isCorrect: true },
      { text: 'Circular en punto muerto para no depender de la tracción del motor', isCorrect: false },
      { text: 'No debe evitarse ninguna maniobra especial si se tienen neumáticos de invierno', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué vehículos son más afectados por el viento lateral fuerte?',
    explanation: 'Los vehículos altos y ligeros son los más vulnerables al viento lateral: furgonetas, caravanas, vehículos con remolque voluminoso, camiones de caja alta y motocicletas. El viento actúa sobre su mayor superficie expuesta y los desestabiliza con más facilidad que a los vehículos bajos y pesados.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 2,
    isTrap: false,
    tags: ['viento lateral', 'furgoneta', 'caravana', 'estabilidad'],
    options: [
      { text: 'Los turismos bajos y los todoterrenos pesados', isCorrect: false },
      { text: 'Solo las motocicletas; los vehículos de 4 ruedas no se ven afectados', isCorrect: false },
      { text: 'Los vehículos altos y ligeros: furgonetas, caravanas, camiones de caja', isCorrect: true },
      { text: 'Los vehículos tracción delantera, ya que el motor se desplaza', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuánto puede llegar a aumentar la distancia de frenado con lluvia intensa respecto a calzada seca?',
    explanation: 'La lluvia mojando la calzada puede duplicar la distancia de frenado respecto a condiciones secas. En condiciones de aquaplaning puede ser aún mayor. Por ello, con lluvia debe aumentarse la distancia de seguridad y reducir la velocidad.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 2,
    isTrap: false,
    tags: ['lluvia', 'distancia frenado', 'duplicar', 'mojada'],
    options: [
      { text: 'Aumenta un 20% respecto a la calzada seca', isCorrect: false },
      { text: 'Puede duplicarse respecto a la distancia en calzada seca', isCorrect: true },
      { text: 'Aumenta solo si los neumáticos tienen menos de 3 mm de dibujo', isCorrect: false },
      { text: 'No varía significativamente con neumáticos en buen estado', isCorrect: false },
    ],
  },
  {
    prompt: 'Con visibilidad extremadamente reducida por niebla y no puedes encontrar una salida cercana. ¿Qué debes hacer?',
    explanation: 'Si la visibilidad es tan reducida que no se puede conducir con seguridad, el conductor debe buscar un lugar seguro fuera de la calzada (área de descanso, arcén amplio) para detenerse completamente, encender las luces de emergencia y esperar a que las condiciones mejoren. Nunca parar en el carril de circulación.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 3,
    isTrap: false,
    tags: ['niebla', 'visibilidad nula', 'parar', 'seguridad'],
    options: [
      { text: 'Activar las luces largas para mejorar la visibilidad hacia adelante', isCorrect: false },
      { text: 'Parar en el carril de circulación y encender los hazards', isCorrect: false },
      { text: 'Buscar un lugar seguro fuera de la calzada, parar y esperar a que mejore', isCorrect: true },
      { text: 'Reducir la velocidad a 20 km/h y continuar pegado a la línea del arcén', isCorrect: false },
    ],
  },
  {
    prompt: 'De noche con lluvia intensa, ¿por qué no debes usar las luces largas aunque tengas poca visibilidad?',
    explanation: 'De noche con lluvia intensa, las luces largas producen el denominado "efecto pantalla": la luz se refracta y dispersa en las gotas de agua en suspensión, creando un muro de luz que deslumbra al conductor y reduce aún más la visibilidad. Las luces de cruce, con su haz más bajo, evitan este problema.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 2,
    isTrap: true,
    tags: ['lluvia', 'noche', 'efecto pantalla', 'luces largas'],
    options: [
      { text: 'Porque las luces largas consumen más batería y pueden dejar el vehículo sin luz', isCorrect: false },
      { text: 'Porque producen efecto pantalla al refractarse en las gotas, empeorando la visión', isCorrect: true },
      { text: 'Porque están prohibidas cuando llueve aunque sea de noche', isCorrect: false },
      { text: 'Porque la lluvia apaga los faros si están encendidos mucho tiempo', isCorrect: false },
    ],
  },
  {
    prompt: '¿En qué parte de la vía se forma antes el hielo y por qué?',
    explanation: 'Los puentes y viaductos son los primeros lugares donde se forma hielo, ya que el aire frío circula tanto por encima como por debajo de la estructura, enfriándola desde ambas caras. En la calzada normal, el suelo conserva el calor del subsuelo, retrasando la formación de hielo.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 2,
    isTrap: false,
    tags: ['hielo', 'puentes', 'viaductos', 'temperatura'],
    options: [
      { text: 'En las curvas, por la mayor humedad que acumula la calzada', isCorrect: false },
      { text: 'En los túneles, por la sombra permanente que no recibe sol', isCorrect: false },
      { text: 'En los puentes y viaductos, porque el frío actúa por ambas caras', isCorrect: true },
      { text: 'En las rectas largas, por la acción del viento que enfría más rápido', isCorrect: false },
    ],
  },
  {
    prompt: 'Sufres un reventón de neumático a 110 km/h en autopista. ¿Cuál es la reacción correcta?',
    explanation: 'Ante un reventón a alta velocidad, se debe mantener la dirección con firmeza, soltar gradualmente el acelerador sin pisar el freno bruscamente, y dejar que el vehículo reduzca su velocidad paulatinamente hasta poder detenerse en el arcén con seguridad. Un frenazo brusco puede provocar la pérdida total del control.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 3,
    isTrap: true,
    tags: ['reventón', 'neumático', 'alta velocidad', 'frenazo'],
    options: [
      { text: 'Frenar a fondo y girar hacia el arcén de inmediato', isCorrect: false },
      { text: 'Soltar el acelerador y dejar que el vehículo frene solo hasta parar en el arcén', isCorrect: true },
      { text: 'Accionar el freno de mano para detener el vehículo de forma controlada', isCorrect: false },
      { text: 'Girar el volante en sentido contrario al derrape para compensar el efecto', isCorrect: false },
    ],
  },
  {
    prompt: 'Quedas atrapado con el vehículo en la nieve en una carretera secundaria. ¿Cuál es el orden correcto de actuación?',
    explanation: 'Si el vehículo queda atrapado en la nieve: 1) Mantener la calma. 2) Señalizar el vehículo con triángulos y ponerse el chaleco reflectante antes de salir. 3) Llamar al número de emergencias (112). 4) Permanecer dentro del vehículo si hay riesgo de hipotermia, con el motor en marcha intermitentemente para calefacción, asegurando que el tubo de escape esté libre de nieve.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 2,
    isTrap: false,
    tags: ['nieve', 'atrapado', 'emergencias', 'triángulos', '112'],
    options: [
      { text: 'Abandonar el vehículo y caminar hasta el núcleo urbano más cercano', isCorrect: false },
      { text: 'Señalizar el vehículo, ponerse chaleco reflectante, llamar al 112 y esperar dentro si hace frío', isCorrect: true },
      { text: 'Intentar sacar el vehículo de la nieve acelerando a fondo varias veces', isCorrect: false },
      { text: 'Dejar el motor en marcha continuamente para tener calefacción sin límite', isCorrect: false },
    ],
  },
  {
    prompt: 'Conduces en una carretera de montaña en invierno. El termómetro exterior marca 2 ºC y está llovizando. ¿Qué riesgo debes considerar?',
    explanation: 'Con temperatura de 2 ºC y lluvia o llovizna, existe riesgo de formación de hielo negro (black ice), especialmente en zonas a la sombra, puentes o curvas. A esa temperatura, el agua puede congelarse al contacto con el asfalto ya frío. El conductor debe reducir la velocidad y evitar maniobras bruscas.',
    category: 'ADVERSE_CONDITIONS',
    difficulty: 3,
    isTrap: false,
    tags: ['montaña', 'invierno', 'hielo negro', '2ºC', 'llovizna'],
    options: [
      { text: 'Ninguno especial; la lluvia elimina el riesgo de hielo', isCorrect: false },
      { text: 'Riesgo de aquaplaning por el exceso de agua en la calzada', isCorrect: false },
      { text: 'Riesgo de hielo negro, especialmente en zonas sombría y puentes', isCorrect: true },
      { text: 'Solo hay riesgo de hielo cuando la temperatura baja de 0 ºC', isCorrect: false },
    ],
  },

  // ─── PARKING — 1 pregunta adicional ──────────────────────────────────────

  {
    prompt: '¿Está permitido estacionar el vehículo sobre un carril bici señalizado?',
    explanation: 'No. Estacionar sobre un carril bici está expresamente prohibido. Hacerlo obliga a los ciclistas a salir al carril de vehículos motorizados, creando un peligro para ellos. Constituye una infracción grave y puede conllevar multa y retirada del vehículo por la grúa.',
    category: 'PARKING',
    difficulty: 1,
    isTrap: false,
    tags: ['aparcamiento', 'carril bici', 'prohibición', 'ciclista'],
    options: [
      { text: 'Sí, si el estacionamiento es inferior a 5 minutos', isCorrect: false },
      { text: 'Sí, si las ruedas no invaden el carril bici completamente', isCorrect: false },
      { text: 'No, estacionar sobre un carril bici está expresamente prohibido', isCorrect: true },
      { text: 'Solo si no hay ciclistas en ese momento', isCorrect: false },
    ],
  },

  // ─── MECHANICS — 1 pregunta adicional ────────────────────────────────────

  {
    prompt: '¿Con qué frecuencia mínima se debe comprobar la presión de los neumáticos?',
    explanation: 'La DGT recomienda revisar la presión de los neumáticos al menos una vez al mes y siempre antes de un viaje largo. La comprobación debe hacerse con el neumático frío (no se debe medir justo después de circular). La presión correcta está indicada en el manual del fabricante y en la pegatina del pilar o tapón del combustible.',
    category: 'MECHANICS',
    difficulty: 2,
    isTrap: false,
    tags: ['presión', 'neumáticos', 'mensual', 'viaje largo', 'frío'],
    options: [
      { text: 'Solo cuando el testigo de presión del cuadro se enciende', isCorrect: false },
      { text: 'Cada 6 meses en la revisión del taller', isCorrect: false },
      { text: 'Al menos una vez al mes y antes de cada viaje largo', isCorrect: true },
      { text: 'Solo cuando el neumático parece visiblemente bajo', isCorrect: false },
    ],
  },

  // ─── INTERSECTIONS — 1 pregunta adicional ────────────────────────────────

  {
    prompt: '¿Cómo debe tratarse un semáforo que está apagado o averiado?',
    explanation: 'Un semáforo averiado o apagado debe tratarse como una señal de STOP: el conductor debe detenerse completamente antes de la línea de detención y ceder el paso a todos los vehículos que circulen por la vía con la que se intersecta, antes de incorporarse con seguridad.',
    category: 'INTERSECTIONS',
    difficulty: 2,
    isTrap: true,
    tags: ['semáforo averiado', 'STOP', 'intersección', 'preferencia'],
    options: [
      { text: 'Como una señal de ceda el paso: reducir velocidad y ceder si hay tráfico', isCorrect: false },
      { text: 'Como una señal de STOP: parar y ceder el paso a todos', isCorrect: true },
      { text: 'El conductor que llega por la derecha siempre tiene preferencia', isCorrect: false },
      { text: 'No existe norma específica; hay que usar el sentido común', isCorrect: false },
    ],
  },

  // ─── FIRST_AID — 1 pregunta adicional ────────────────────────────────────

  {
    prompt: 'Llegas a un accidente de tráfico y hay un herido en el vehículo. ¿Cuándo está justificado moverle?',
    explanation: 'Un herido en un accidente NO debe moverse a menos que haya un peligro inmediato e inminente para su vida (fuego, riesgo de hundimiento, inmersión en agua). Mover a un herido de forma incorrecta puede agravar lesiones en la columna vertebral y causar parálisis. Lo correcto es llamar al 112 y esperar a los servicios de emergencia.',
    category: 'FIRST_AID',
    difficulty: 2,
    isTrap: true,
    tags: ['herido', 'mover', 'columna', 'emergencia', 'peligro inmediato'],
    options: [
      { text: 'Siempre, para ponerle en posición de seguridad lateral', isCorrect: false },
      { text: 'Solo si está inconsciente y respira con dificultad', isCorrect: false },
      { text: 'Solo si hay peligro inmediato (fuego, hundimiento, inundación)', isCorrect: true },
      { text: 'Nunca; hay que esperar siempre al 112 sin hacer nada', isCorrect: false },
    ],
  },

];
