import type { QuestionCategory } from '../src/generated/prisma/client';

export interface SeedQuestion {
  prompt: string;
  explanation: string;
  category: QuestionCategory;
  difficulty: 1 | 2 | 3 | 4 | 5;
  isTrap: boolean;
  tags: string[];
  options: Array<{ text: string; isCorrect: boolean }>;
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  // ─── VELOCIDAD ───
  {
    prompt: 'En una vía interurbana convencional sin arcén o con arcén menor de 1,5 m, ¿cuál es la velocidad máxima genérica para turismos?',
    explanation: 'Desde 2019 la velocidad máxima en vías convencionales (carreteras de un solo carril por sentido) es 90 km/h, independientemente del arcén. Es una pregunta trampa típica porque mucha gente sigue contestando 100 km/h.',
    category: 'SPEED',
    difficulty: 3,
    isTrap: true,
    tags: ['velocidad', 'interurbana', 'convencional'],
    options: [
      { text: '70 km/h', isCorrect: false },
      { text: '90 km/h', isCorrect: true },
      { text: '100 km/h', isCorrect: false },
      { text: '80 km/h', isCorrect: false },
    ],
  },
  {
    prompt: 'En autopista, un turismo sin remolque puede circular a un máximo genérico de...',
    explanation: 'En autopistas y autovías el límite genérico para turismos es 120 km/h.',
    category: 'SPEED',
    difficulty: 1,
    isTrap: false,
    tags: ['velocidad', 'autopista'],
    options: [
      { text: '100 km/h', isCorrect: false },
      { text: '110 km/h', isCorrect: false },
      { text: '120 km/h', isCorrect: true },
      { text: '130 km/h', isCorrect: false },
    ],
  },
  {
    prompt: 'En una travesía (zona urbana en carretera convencional), la velocidad máxima genérica es...',
    explanation: 'Las travesías se consideran zona urbana. Aplica el límite urbano: 50 km/h, salvo señalización específica.',
    category: 'SPEED',
    difficulty: 3,
    isTrap: true,
    tags: ['velocidad', 'travesía', 'urbano'],
    options: [
      { text: '90 km/h', isCorrect: false },
      { text: '70 km/h', isCorrect: false },
      { text: '50 km/h', isCorrect: true },
      { text: '30 km/h', isCorrect: false },
    ],
  },
  {
    prompt: 'En vías urbanas con un único carril por sentido, ¿cuál es la velocidad máxima genérica?',
    explanation: 'Desde mayo de 2021 las vías urbanas con un solo carril por sentido tienen límite genérico de 30 km/h. Si tiene plataforma única con peatones, 20 km/h.',
    category: 'SPEED',
    difficulty: 2,
    isTrap: false,
    tags: ['velocidad', 'urbano', '30'],
    options: [
      { text: '50 km/h', isCorrect: false },
      { text: '30 km/h', isCorrect: true },
      { text: '40 km/h', isCorrect: false },
      { text: '20 km/h', isCorrect: false },
    ],
  },
  {
    prompt: 'Vas a adelantar a un ciclista por una vía convencional. ¿Puedes superar la velocidad máxima del tramo?',
    explanation: 'Sí, está permitido rebasar en 20 km/h la velocidad máxima genérica para adelantar a un vehículo más lento, pero NO para adelantar a peatones, ciclos, ciclomotores ni vehículos especiales. Y nunca en autopistas.',
    category: 'SPEED',
    difficulty: 4,
    isTrap: true,
    tags: ['adelantamiento', 'ciclistas', 'velocidad'],
    options: [
      { text: 'Sí, puedo rebasar en 20 km/h el límite', isCorrect: false },
      { text: 'No, en ningún caso puedo superarlo al adelantar a un ciclista', isCorrect: true },
      { text: 'Sí, hasta el doble del límite', isCorrect: false },
      { text: 'Solo en autovías', isCorrect: false },
    ],
  },

  // ─── ALCOHOL Y DROGAS ───
  {
    prompt: '¿Cuál es la tasa máxima de alcohol en aire espirado para un conductor con permiso de menos de 2 años?',
    explanation: 'Los conductores noveles (menos de 2 años) y los profesionales tienen una tasa máxima de 0,15 mg/l en aire espirado (0,3 g/l en sangre).',
    category: 'ALCOHOL_DRUGS',
    difficulty: 2,
    isTrap: false,
    tags: ['alcohol', 'noveles'],
    options: [
      { text: '0,25 mg/l', isCorrect: false },
      { text: '0,15 mg/l', isCorrect: true },
      { text: '0,30 mg/l', isCorrect: false },
      { text: '0,00 mg/l', isCorrect: false },
    ],
  },
  {
    prompt: 'Conducir con una tasa de alcohol entre 0,25 y 0,50 mg/l en aire espirado conlleva...',
    explanation: 'Es infracción grave: multa de 500 € y 4 puntos del carnet. A partir de 0,50 mg/l (o el doble del permitido para noveles) es delito penal.',
    category: 'ALCOHOL_DRUGS',
    difficulty: 3,
    isTrap: false,
    tags: ['alcohol', 'sanción', 'puntos'],
    options: [
      { text: 'Multa de 200 € y 2 puntos', isCorrect: false },
      { text: 'Multa de 500 € y 4 puntos', isCorrect: true },
      { text: 'Multa de 1000 € y retirada del carnet', isCorrect: false },
      { text: 'Solo advertencia', isCorrect: false },
    ],
  },
  {
    prompt: 'Tras la ingesta de alcohol, ¿qué efecto NO se produce?',
    explanation: 'El alcohol REDUCE los reflejos, NO los aumenta. También aumenta el tiempo de reacción y disminuye el campo visual.',
    category: 'ALCOHOL_DRUGS',
    difficulty: 2,
    isTrap: true,
    tags: ['alcohol', 'efectos'],
    options: [
      { text: 'Aumento del tiempo de reacción', isCorrect: false },
      { text: 'Aumento de los reflejos', isCorrect: true },
      { text: 'Reducción del campo visual', isCorrect: false },
      { text: 'Exceso de confianza', isCorrect: false },
    ],
  },
  {
    prompt: '¿Puede un agente obligarle a realizar la prueba de detección de drogas si no presenta síntomas evidentes?',
    explanation: 'Sí. Los agentes pueden realizar pruebas preventivas de drogas a cualquier conductor, incluso sin síntomas o sin haber cometido infracción.',
    category: 'ALCOHOL_DRUGS',
    difficulty: 4,
    isTrap: true,
    tags: ['drogas', 'controles'],
    options: [
      { text: 'No, solo si hay síntomas evidentes', isCorrect: false },
      { text: 'No, solo tras un accidente', isCorrect: false },
      { text: 'Sí, puede hacerse de forma preventiva', isCorrect: true },
      { text: 'Solo si lo ordena un juez', isCorrect: false },
    ],
  },

  // ─── SEÑALES ───
  {
    prompt: 'Una señal triangular con borde rojo indica...',
    explanation: 'Las señales triangulares con borde rojo son señales de PELIGRO o advertencia. Las redondas con borde rojo son prohibición.',
    category: 'SIGNALS',
    difficulty: 1,
    isTrap: false,
    tags: ['señales', 'peligro'],
    options: [
      { text: 'Prohibición', isCorrect: false },
      { text: 'Peligro', isCorrect: true },
      { text: 'Obligación', isCorrect: false },
      { text: 'Información', isCorrect: false },
    ],
  },
  {
    prompt: 'Una señal cuadrada o rectangular azul con un símbolo blanco indica...',
    explanation: 'Las señales cuadradas/rectangulares azules con símbolo blanco son INDICACIÓN o información. Las circulares azules son obligación.',
    category: 'SIGNALS',
    difficulty: 2,
    isTrap: true,
    tags: ['señales', 'indicación'],
    options: [
      { text: 'Obligación', isCorrect: false },
      { text: 'Indicación o información', isCorrect: true },
      { text: 'Prohibición', isCorrect: false },
      { text: 'Peligro especial', isCorrect: false },
    ],
  },
  {
    prompt: 'La señal de STOP obliga a...',
    explanation: 'La señal de STOP obliga a DETENERSE completamente y ceder el paso, aunque la vía esté vacía. Pararse no es lo mismo que reducir la velocidad.',
    category: 'SIGNALS',
    difficulty: 1,
    isTrap: false,
    tags: ['stop', 'prioridad'],
    options: [
      { text: 'Reducir la velocidad y ceder el paso', isCorrect: false },
      { text: 'Detenerse completamente y ceder el paso', isCorrect: true },
      { text: 'Continuar con precaución', isCorrect: false },
      { text: 'Detenerse solo si hay tráfico', isCorrect: false },
    ],
  },
  {
    prompt: 'Una línea longitudinal continua blanca en el centro de la calzada significa...',
    explanation: 'No puede rebasarse ni pisarse, salvo para acceder a una propiedad o lugar fuera de la calzada. Está terminantemente prohibido adelantar cruzándola.',
    category: 'SIGNALS',
    difficulty: 2,
    isTrap: false,
    tags: ['marcas', 'línea continua'],
    options: [
      { text: 'Se puede rebasar si no hay tráfico', isCorrect: false },
      { text: 'No puede rebasarse ni pisarse', isCorrect: true },
      { text: 'Solo prohíbe el adelantamiento', isCorrect: false },
      { text: 'Se puede pisar pero no cruzar', isCorrect: false },
    ],
  },
  {
    prompt: 'Una señal circular blanca con borde rojo y un número en su interior indica...',
    explanation: 'Es una señal de prohibición de velocidad máxima.',
    category: 'SIGNALS',
    difficulty: 1,
    isTrap: false,
    tags: ['señales', 'velocidad'],
    options: [
      { text: 'Velocidad mínima', isCorrect: false },
      { text: 'Velocidad máxima permitida', isCorrect: true },
      { text: 'Velocidad recomendada', isCorrect: false },
      { text: 'Distancia al siguiente pueblo', isCorrect: false },
    ],
  },
  {
    prompt: 'Una señal azul circular con un número blanco indica...',
    explanation: 'Las señales circulares azules indican OBLIGACIÓN. Un número blanco indica velocidad MÍNIMA obligatoria.',
    category: 'SIGNALS',
    difficulty: 3,
    isTrap: true,
    tags: ['señales', 'obligación', 'velocidad mínima'],
    options: [
      { text: 'Velocidad máxima', isCorrect: false },
      { text: 'Velocidad mínima obligatoria', isCorrect: true },
      { text: 'Velocidad recomendada', isCorrect: false },
      { text: 'Distancia mínima entre vehículos', isCorrect: false },
    ],
  },

  // ─── PRIORIDAD ───
  {
    prompt: 'En una intersección no señalizada, ¿quién tiene prioridad?',
    explanation: 'En intersecciones sin señalización, la prioridad es para el vehículo que viene por la DERECHA del conductor.',
    category: 'PRIORITY',
    difficulty: 1,
    isTrap: false,
    tags: ['prioridad', 'intersección'],
    options: [
      { text: 'El que viene por la izquierda', isCorrect: false },
      { text: 'El que viene por la derecha', isCorrect: true },
      { text: 'El que va más rápido', isCorrect: false },
      { text: 'El que llega primero', isCorrect: false },
    ],
  },
  {
    prompt: 'Un tranvía y un turismo llegan simultáneamente a una intersección sin semáforos. ¿Quién tiene prioridad?',
    explanation: 'El tranvía siempre tiene prioridad sobre el resto de vehículos, salvo señalización en sentido contrario.',
    category: 'PRIORITY',
    difficulty: 2,
    isTrap: false,
    tags: ['prioridad', 'tranvía'],
    options: [
      { text: 'El turismo si viene por la derecha', isCorrect: false },
      { text: 'El tranvía siempre', isCorrect: true },
      { text: 'El que llegue primero', isCorrect: false },
      { text: 'Ambos deben detenerse', isCorrect: false },
    ],
  },
  {
    prompt: 'Circulando por una glorieta y otro vehículo va a entrar, ¿quién tiene prioridad?',
    explanation: 'En las glorietas tiene prioridad quien YA está circulando dentro. El que va a entrar debe ceder el paso.',
    category: 'ROUNDABOUTS',
    difficulty: 1,
    isTrap: false,
    tags: ['glorieta', 'prioridad'],
    options: [
      { text: 'El que va a entrar', isCorrect: false },
      { text: 'El que ya circula por la glorieta', isCorrect: true },
      { text: 'El de mayor tamaño', isCorrect: false },
      { text: 'El que viene por la derecha', isCorrect: false },
    ],
  },
  {
    prompt: 'En una vía con la señal de "ceda el paso" debe...',
    explanation: 'Ceder el paso NO obliga necesariamente a detenerse, solo a no estorbar a quienes circulen por la vía con prioridad. Si están libres, puede continuar sin parar.',
    category: 'PRIORITY',
    difficulty: 3,
    isTrap: true,
    tags: ['ceda', 'prioridad'],
    options: [
      { text: 'Detenerse siempre completamente', isCorrect: false },
      { text: 'Ceder el paso sin necesidad de detenerse si está libre', isCorrect: true },
      { text: 'Pasar con precaución sin reducir', isCorrect: false },
      { text: 'Tocar la bocina para avisar', isCorrect: false },
    ],
  },
  {
    prompt: 'Un vehículo policial con señales luminosas y acústicas en servicio urgente...',
    explanation: 'Los vehículos prioritarios en servicio urgente tienen preferencia sobre el resto y pueden incumplir señales/velocidad SIEMPRE QUE LLEVEN señales luminosas Y acústicas.',
    category: 'PRIORITY',
    difficulty: 2,
    isTrap: false,
    tags: ['prioritarios', 'emergencias'],
    options: [
      { text: 'Tiene prioridad sobre todos los demás vehículos', isCorrect: true },
      { text: 'Cede el paso como cualquier vehículo', isCorrect: false },
      { text: 'Solo si lo conduce un agente', isCorrect: false },
      { text: 'Solo en vía urbana', isCorrect: false },
    ],
  },

  // ─── ADELANTAMIENTOS ───
  {
    prompt: 'Está PROHIBIDO adelantar en...',
    explanation: 'Está prohibido adelantar en cambios de rasante de visibilidad reducida, curvas con visibilidad reducida, túneles, pasos a nivel, pasos para peatones, intersecciones (salvo glorietas) y cuando exista línea continua.',
    category: 'OVERTAKING',
    difficulty: 2,
    isTrap: false,
    tags: ['adelantamiento', 'prohibición'],
    options: [
      { text: 'Curvas de visibilidad reducida y cambios de rasante', isCorrect: true },
      { text: 'Carreteras de dos carriles por sentido', isCorrect: false },
      { text: 'Cualquier vía interurbana', isCorrect: false },
      { text: 'Solo de noche', isCorrect: false },
    ],
  },
  {
    prompt: 'Al adelantar a un ciclista en vía interurbana, debe...',
    explanation: 'Debe dejar al menos 1,5 metros de separación lateral. Y se permite ocupar parcialmente el carril contrario, INCLUSO pisando línea continua si es seguro y no obstaculiza a otros.',
    category: 'OVERTAKING',
    difficulty: 3,
    isTrap: false,
    tags: ['adelantamiento', 'ciclista', '1.5m'],
    options: [
      { text: 'Dejar al menos 50 cm de separación', isCorrect: false },
      { text: 'Dejar al menos 1,5 m de separación lateral', isCorrect: true },
      { text: 'Dejar 1 m si no hay tráfico', isCorrect: false },
      { text: 'No es obligatoria distancia mínima', isCorrect: false },
    ],
  },
  {
    prompt: 'Durante un adelantamiento, advierte que un vehículo se le acerca por detrás más rápido. Debe...',
    explanation: 'Quien inició el adelantamiento primero tiene prioridad. Debe TERMINAR el adelantamiento normalmente sin acelerar bruscamente ni desviarse. El de atrás debe esperar.',
    category: 'OVERTAKING',
    difficulty: 4,
    isTrap: true,
    tags: ['adelantamiento', 'maniobra'],
    options: [
      { text: 'Acelerar bruscamente para terminar antes', isCorrect: false },
      { text: 'Abortar el adelantamiento y volver al carril', isCorrect: false },
      { text: 'Terminar el adelantamiento con normalidad', isCorrect: true },
      { text: 'Detenerse en el carril contrario', isCorrect: false },
    ],
  },
  {
    prompt: 'Antes de iniciar un adelantamiento, ¿qué debe comprobar?',
    explanation: 'Debe verificar visibilidad y espacio suficientes, que nadie haya iniciado un adelantamiento sobre usted, y señalizar con el intermitente izquierdo.',
    category: 'OVERTAKING',
    difficulty: 1,
    isTrap: false,
    tags: ['adelantamiento', 'precauciones'],
    options: [
      { text: 'Solo el intermitente', isCorrect: false },
      { text: 'Visibilidad, espacio, retrovisores y señalizar', isCorrect: true },
      { text: 'Solo el espejo retrovisor central', isCorrect: false },
      { text: 'Nada, basta con acelerar', isCorrect: false },
    ],
  },

  // ─── DOCUMENTACIÓN ───
  {
    prompt: 'El permiso de circulación lo expide...',
    explanation: 'El permiso de circulación lo expide la Jefatura Provincial de Tráfico al matricular el vehículo. La ITV emite la ficha técnica.',
    category: 'DOCUMENTATION',
    difficulty: 3,
    isTrap: true,
    tags: ['documentos', 'permiso circulación'],
    options: [
      { text: 'El fabricante del vehículo', isCorrect: false },
      { text: 'La Jefatura Provincial de Tráfico', isCorrect: true },
      { text: 'La compañía aseguradora', isCorrect: false },
      { text: 'La ITV', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuántos puntos tiene un conductor novel al obtener el carnet por primera vez?',
    explanation: 'Los conductores noveles empiezan con 8 puntos. A los 3 años (si no han sido sancionados) suben a 12.',
    category: 'DOCUMENTATION',
    difficulty: 2,
    isTrap: false,
    tags: ['puntos', 'novel'],
    options: [
      { text: '12 puntos', isCorrect: false },
      { text: '10 puntos', isCorrect: false },
      { text: '8 puntos', isCorrect: true },
      { text: '6 puntos', isCorrect: false },
    ],
  },
  {
    prompt: 'El seguro obligatorio del vehículo cubre...',
    explanation: 'El seguro obligatorio (SOA) cubre la responsabilidad civil por DAÑOS A TERCEROS, no los daños propios ni los del conductor culpable.',
    category: 'DOCUMENTATION',
    difficulty: 2,
    isTrap: true,
    tags: ['seguro'],
    options: [
      { text: 'Todos los daños del vehículo', isCorrect: false },
      { text: 'Responsabilidad civil por daños a terceros', isCorrect: true },
      { text: 'Solo daños del conductor', isCorrect: false },
      { text: 'Robo del vehículo', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cada cuánto debe pasar la ITV un turismo de menos de 4 años?',
    explanation: 'Los turismos no pasan ITV hasta cumplir 4 años. Entre 4 y 10 años, cada 2 años. A partir de 10 años, anualmente.',
    category: 'DOCUMENTATION',
    difficulty: 2,
    isTrap: false,
    tags: ['itv'],
    options: [
      { text: 'Cada año', isCorrect: false },
      { text: 'Cada 2 años', isCorrect: false },
      { text: 'No pasa ITV hasta los 4 años', isCorrect: true },
      { text: 'Cada 5 años', isCorrect: false },
    ],
  },

  // ─── SEGURIDAD VIAL ───
  {
    prompt: 'El uso del cinturón de seguridad es obligatorio...',
    explanation: 'Es obligatorio para TODOS los ocupantes del vehículo, delante y detrás, en cualquier tipo de vía.',
    category: 'ROAD_SAFETY',
    difficulty: 1,
    isTrap: false,
    tags: ['cinturón'],
    options: [
      { text: 'Solo en asientos delanteros', isCorrect: false },
      { text: 'Para todos los ocupantes del vehículo', isCorrect: true },
      { text: 'Solo fuera de zona urbana', isCorrect: false },
      { text: 'Solo en viajes largos', isCorrect: false },
    ],
  },
  {
    prompt: 'Un niño de 1,30 m de altura debe viajar...',
    explanation: 'Los menores de 1,35 m DEBEN usar sistema de retención infantil homologado y viajar en asientos traseros (salvo excepciones).',
    category: 'ROAD_SAFETY',
    difficulty: 2,
    isTrap: false,
    tags: ['niños', 'sillas'],
    options: [
      { text: 'Delante sin restricciones', isCorrect: false },
      { text: 'Con cinturón normal en asientos traseros', isCorrect: false },
      { text: 'Con sistema de retención infantil homologado en plazas traseras', isCorrect: true },
      { text: 'En el regazo de un adulto', isCorrect: false },
    ],
  },
  {
    prompt: 'La distancia de seguridad con el vehículo precedente debe permitir...',
    explanation: 'La distancia de seguridad debe permitir detenerse sin chocar en caso de frenado brusco del vehículo precedente.',
    category: 'ROAD_SAFETY',
    difficulty: 1,
    isTrap: false,
    tags: ['distancia'],
    options: [
      { text: 'Adelantarle con facilidad', isCorrect: false },
      { text: 'Detenerse en caso de frenada brusca del de delante', isCorrect: true },
      { text: 'Verle por el retrovisor central', isCorrect: false },
      { text: 'Ahorrar combustible', isCorrect: false },
    ],
  },
  {
    prompt: 'En un vehículo, los reposacabezas...',
    explanation: 'Los reposacabezas previenen lesiones cervicales (latigazo). Deben estar ajustados a la altura de la cabeza, no del cuello.',
    category: 'ROAD_SAFETY',
    difficulty: 2,
    isTrap: false,
    tags: ['reposacabezas'],
    options: [
      { text: 'Son un accesorio decorativo', isCorrect: false },
      { text: 'Previenen lesiones cervicales en caso de impacto', isCorrect: true },
      { text: 'Solo son útiles en viajes largos', isCorrect: false },
      { text: 'Sirven para apoyar la cabeza al dormir', isCorrect: false },
    ],
  },
  {
    prompt: 'En caso de avería en autopista, ¿qué debe hacer primero?',
    explanation: 'Salir del coche por el lado contrario al tráfico, ponerse el chaleco reflectante ANTES de salir y colocar triángulos.',
    category: 'ROAD_SAFETY',
    difficulty: 3,
    isTrap: true,
    tags: ['avería', 'emergencias', 'chaleco'],
    options: [
      { text: 'Salir del coche y colocar los triángulos', isCorrect: false },
      { text: 'Ponerse el chaleco reflectante antes de bajarse', isCorrect: true },
      { text: 'Llamar a la grúa primero', isCorrect: false },
      { text: 'Empujar el coche al arcén', isCorrect: false },
    ],
  },

  // ─── GLORIETAS ───
  {
    prompt: 'En una glorieta de dos carriles, para salir por la tercera salida debe circular por...',
    explanation: 'Para salidas alejadas (3ª, 4ª) se utiliza el carril interior; se sale aproximándose al exterior con antelación señalizando.',
    category: 'ROUNDABOUTS',
    difficulty: 3,
    isTrap: false,
    tags: ['glorieta', 'carriles'],
    options: [
      { text: 'Carril exterior siempre', isCorrect: false },
      { text: 'Carril interior, aproximándose al exterior antes de salir', isCorrect: true },
      { text: 'Cualquier carril', isCorrect: false },
      { text: 'Carril central si lo hay', isCorrect: false },
    ],
  },
  {
    prompt: 'Antes de salir de una glorieta debe...',
    explanation: 'Señalizar con el intermitente derecho la intención de salir.',
    category: 'ROUNDABOUTS',
    difficulty: 1,
    isTrap: false,
    tags: ['glorieta', 'intermitente'],
    options: [
      { text: 'Señalizar con el intermitente izquierdo', isCorrect: false },
      { text: 'Señalizar con el intermitente derecho', isCorrect: true },
      { text: 'No es necesario señalizar', isCorrect: false },
      { text: 'Tocar la bocina', isCorrect: false },
    ],
  },
  {
    prompt: 'Circulando por una glorieta, ¿debe señalizar con intermitente al pasar por enfrente de salidas que no va a tomar?',
    explanation: 'Mientras circula dentro de la glorieta NO debe señalizar; solo señaliza el intermitente derecho ANTES de la salida que va a tomar.',
    category: 'ROUNDABOUTS',
    difficulty: 3,
    isTrap: true,
    tags: ['glorieta', 'señalización'],
    options: [
      { text: 'Sí, intermitente izquierdo continuamente', isCorrect: false },
      { text: 'No, solo señalizo el derecho antes de mi salida', isCorrect: true },
      { text: 'Sí, intermitente derecho en cada salida', isCorrect: false },
      { text: 'Solo si hay vehículos detrás', isCorrect: false },
    ],
  },

  // ─── ESTACIONAMIENTO ───
  {
    prompt: 'Está PROHIBIDO estacionar a una distancia menor de... de un paso de peatones.',
    explanation: 'No puede estacionar dentro de los 5 m anteriores a un paso de peatones o cruce.',
    category: 'PARKING',
    difficulty: 2,
    isTrap: false,
    tags: ['estacionamiento', 'paso peatones'],
    options: [
      { text: '2 metros', isCorrect: false },
      { text: '5 metros', isCorrect: true },
      { text: '10 metros', isCorrect: false },
      { text: '15 metros', isCorrect: false },
    ],
  },
  {
    prompt: '¿Está permitido estacionar en una zona reservada para minusválidos si vuelve "en seguida"?',
    explanation: 'No. Las zonas reservadas para personas con movilidad reducida solo pueden ser usadas por quienes tengan la tarjeta de estacionamiento correspondiente.',
    category: 'PARKING',
    difficulty: 1,
    isTrap: false,
    tags: ['estacionamiento', 'minusválidos'],
    options: [
      { text: 'Sí, si es menos de 5 minutos', isCorrect: false },
      { text: 'No, en ningún caso sin tarjeta', isCorrect: true },
      { text: 'Sí, si dejo los intermitentes', isCorrect: false },
      { text: 'Solo de noche', isCorrect: false },
    ],
  },
  {
    prompt: 'Detenerse y estacionarse son lo mismo si la duración es...',
    explanation: 'La parada es una inmovilización menor de 2 minutos sin abandonar el vehículo. Más de eso, o abandonando el vehículo, ya es estacionamiento.',
    category: 'PARKING',
    difficulty: 3,
    isTrap: true,
    tags: ['parada', 'estacionamiento'],
    options: [
      { text: 'Menor de 5 minutos', isCorrect: false },
      { text: 'Mayor de 2 minutos o abandonando el vehículo', isCorrect: true },
      { text: 'Solo en zona azul', isCorrect: false },
      { text: 'Nunca son lo mismo', isCorrect: false },
    ],
  },

  // ─── INTERSECCIONES ───
  {
    prompt: 'En una intersección con semáforo en ámbar fijo, ¿qué debe hacer?',
    explanation: 'El ámbar fijo obliga a detenerse, SALVO si al encenderse el vehículo ya está tan cerca que no puede detenerse con seguridad.',
    category: 'INTERSECTIONS',
    difficulty: 2,
    isTrap: true,
    tags: ['semáforo', 'ámbar'],
    options: [
      { text: 'Acelerar para pasar antes del rojo', isCorrect: false },
      { text: 'Detenerse, salvo que esté tan cerca que no pueda hacerlo con seguridad', isCorrect: true },
      { text: 'Continuar con normalidad, equivale al verde', isCorrect: false },
      { text: 'Detenerse siempre, sin excepción', isCorrect: false },
    ],
  },
  {
    prompt: 'Un semáforo ámbar intermitente significa...',
    explanation: 'El ámbar intermitente obliga a circular con precaución, no implica obligación de detenerse. Las normas de prioridad habituales se mantienen.',
    category: 'INTERSECTIONS',
    difficulty: 2,
    isTrap: false,
    tags: ['semáforo', 'intermitente'],
    options: [
      { text: 'Obligación de detenerse', isCorrect: false },
      { text: 'Precaución, las normas de prioridad siguen vigentes', isCorrect: true },
      { text: 'Lo mismo que el rojo', isCorrect: false },
      { text: 'Lo mismo que el verde', isCorrect: false },
    ],
  },
  {
    prompt: 'En una intersección regulada por agente y semáforo, ¿quién manda?',
    explanation: 'El orden de prioridad es: agente > semáforo > señal vertical > marca vial. El agente siempre prevalece.',
    category: 'INTERSECTIONS',
    difficulty: 1,
    isTrap: false,
    tags: ['agente', 'prioridad', 'semáforo'],
    options: [
      { text: 'El semáforo', isCorrect: false },
      { text: 'El agente', isCorrect: true },
      { text: 'La señal vertical', isCorrect: false },
      { text: 'El conductor decide', isCorrect: false },
    ],
  },

  // ─── CONDUCCIÓN EFICIENTE ───
  {
    prompt: 'Para una conducción más eficiente al arrancar el motor...',
    explanation: 'No es necesario calentar el motor parado. Es más eficiente arrancar y empezar a circular suavemente al cabo de unos segundos.',
    category: 'EFFICIENT_DRIVING',
    difficulty: 2,
    isTrap: true,
    tags: ['eficiencia', 'arranque'],
    options: [
      { text: 'Calentar el motor 2-3 minutos parado', isCorrect: false },
      { text: 'Arrancar y circular suavemente tras unos segundos', isCorrect: true },
      { text: 'Acelerar a fondo para calentarlo rápido', isCorrect: false },
      { text: 'Encenderlo y apagarlo varias veces', isCorrect: false },
    ],
  },
  {
    prompt: 'Para reducir el consumo, lo más adecuado es...',
    explanation: 'Circular en las marchas más largas posibles a régimen bajo (1500-2500 rpm gasolina, 1200-2000 diésel). Y mantener una velocidad constante.',
    category: 'EFFICIENT_DRIVING',
    difficulty: 2,
    isTrap: false,
    tags: ['eficiencia', 'consumo'],
    options: [
      { text: 'Circular en marchas largas a régimen bajo', isCorrect: true },
      { text: 'Acelerar y frenar frecuentemente', isCorrect: false },
      { text: 'Circular siempre en 2ª marcha', isCorrect: false },
      { text: 'Acelerar al máximo en cada cambio', isCorrect: false },
    ],
  },

  // ─── MECÁNICA ───
  {
    prompt: 'La presión correcta de los neumáticos figura en...',
    explanation: 'La presión recomendada figura en el manual del vehículo y en una etiqueta del fabricante (puerta del conductor o tapa del depósito).',
    category: 'MECHANICS',
    difficulty: 2,
    isTrap: false,
    tags: ['neumáticos'],
    options: [
      { text: 'En el flanco del neumático', isCorrect: false },
      { text: 'En el manual del vehículo y la etiqueta del fabricante', isCorrect: true },
      { text: 'En el permiso de circulación', isCorrect: false },
      { text: 'En la ITV', isCorrect: false },
    ],
  },
  {
    prompt: 'La profundidad mínima legal del dibujo de los neumáticos de un turismo es...',
    explanation: 'La profundidad mínima legal en España es 1,6 mm. Por seguridad se recomienda cambiarlos a partir de 3 mm.',
    category: 'MECHANICS',
    difficulty: 2,
    isTrap: false,
    tags: ['neumáticos'],
    options: [
      { text: '1,6 mm', isCorrect: true },
      { text: '3 mm', isCorrect: false },
      { text: '0,8 mm', isCorrect: false },
      { text: '2,5 mm', isCorrect: false },
    ],
  },
  {
    prompt: 'Si se enciende el testigo rojo de presión de aceite mientras circula, debe...',
    explanation: 'Es una señal grave. Debe detenerse cuanto antes en lugar seguro, apagar el motor y revisar. Continuar puede destruir el motor.',
    category: 'MECHANICS',
    difficulty: 2,
    isTrap: false,
    tags: ['testigos', 'aceite'],
    options: [
      { text: 'Continuar hasta el destino', isCorrect: false },
      { text: 'Detenerse cuanto antes en lugar seguro y apagar el motor', isCorrect: true },
      { text: 'Acelerar para que el aceite circule', isCorrect: false },
      { text: 'Esperar a que se apague solo', isCorrect: false },
    ],
  },

  // ─── PRIMEROS AUXILIOS ───
  {
    prompt: 'Ante un accidente con heridos, lo primero que debe hacer es...',
    explanation: 'La regla PAS: Proteger (zona, chaleco, triángulos), Avisar (112) y Socorrer. Proteger SIEMPRE antes de acercarse a los heridos.',
    category: 'FIRST_AID',
    difficulty: 2,
    isTrap: true,
    tags: ['accidente', 'PAS'],
    options: [
      { text: 'Sacar a los heridos del coche inmediatamente', isCorrect: false },
      { text: 'Proteger la zona, avisar al 112 y luego socorrer (PAS)', isCorrect: true },
      { text: 'Llamar a la familia', isCorrect: false },
      { text: 'Hacer fotos para el seguro', isCorrect: false },
    ],
  },
  {
    prompt: 'En un accidente, ¿se debe sacar el casco a un motorista herido?',
    explanation: 'Como norma general NO. Solo si es imprescindible para reanimación cardiopulmonar y siempre entre dos personas con técnica adecuada.',
    category: 'FIRST_AID',
    difficulty: 3,
    isTrap: true,
    tags: ['casco', 'moto', 'accidente'],
    options: [
      { text: 'Sí, siempre y rápidamente', isCorrect: false },
      { text: 'No, salvo que sea imprescindible para reanimar', isCorrect: true },
      { text: 'Sí, si está consciente', isCorrect: false },
      { text: 'Sí, solo si sangra', isCorrect: false },
    ],
  },
  {
    prompt: 'Ante un herido inconsciente que respira, la posición recomendada es...',
    explanation: 'La posición lateral de seguridad (PLS) evita atragantamiento si vomita y mantiene la vía aérea abierta.',
    category: 'FIRST_AID',
    difficulty: 2,
    isTrap: false,
    tags: ['primeros auxilios', 'PLS'],
    options: [
      { text: 'Boca arriba', isCorrect: false },
      { text: 'Posición lateral de seguridad', isCorrect: true },
      { text: 'Sentado', isCorrect: false },
      { text: 'Boca abajo', isCorrect: false },
    ],
  },

  // ─── EXTRA / TRAMPAS ───
  {
    prompt: 'En una autovía urbana, ¿pueden circular peatones?',
    explanation: 'No. En autopistas y autovías está PROHIBIDO el tránsito de peatones, ciclos, ciclomotores, vehículos de tracción animal y agrícolas.',
    category: 'ROAD_SAFETY',
    difficulty: 3,
    isTrap: true,
    tags: ['autovía', 'peatones'],
    options: [
      { text: 'Sí, por el arcén', isCorrect: false },
      { text: 'No, está prohibido', isCorrect: true },
      { text: 'Sí, solo de día', isCorrect: false },
      { text: 'Sí, si llevan chaleco', isCorrect: false },
    ],
  },
  {
    prompt: 'El uso del teléfono móvil al volante está permitido...',
    explanation: 'Solo está permitido con dispositivo manos libres que NO requiera sostener el aparato. Sostener el móvil con la mano, aunque sea para mirar el GPS, es infracción grave (6 puntos y 200€).',
    category: 'ROAD_SAFETY',
    difficulty: 2,
    isTrap: true,
    tags: ['móvil', 'distracciones'],
    options: [
      { text: 'Con auriculares siempre que no sean inalámbricos', isCorrect: false },
      { text: 'Con manos libres que no requiera sostener el aparato', isCorrect: true },
      { text: 'Si va a baja velocidad', isCorrect: false },
      { text: 'Solo en cruces', isCorrect: false },
    ],
  },
  {
    prompt: 'En vía interurbana, ¿debe llevar luces encendidas durante el día?',
    explanation: 'Las motos SÍ tienen obligación de luces de cruce o diurnas siempre. Los turismos, no obligatoriamente de día (salvo túneles, lluvia intensa, etc.), pero las DRL están recomendadas.',
    category: 'ROAD_SAFETY',
    difficulty: 4,
    isTrap: true,
    tags: ['luces', 'día'],
    options: [
      { text: 'Sí, los turismos están obligados siempre', isCorrect: false },
      { text: 'No, los turismos no obligatoriamente; las motos sí', isCorrect: true },
      { text: 'Sí, las largas siempre', isCorrect: false },
      { text: 'Solo si llueve', isCorrect: false },
    ],
  },
  {
    prompt: 'Al circular por un túnel, debe encender...',
    explanation: 'Es obligatorio el alumbrado de cruce (luz corta) en TODOS los túneles, incluso si están bien iluminados.',
    category: 'ROAD_SAFETY',
    difficulty: 2,
    isTrap: false,
    tags: ['túnel', 'luces'],
    options: [
      { text: 'Luces de posición solamente', isCorrect: false },
      { text: 'Luces de cruce (cortas)', isCorrect: true },
      { text: 'Luces largas', isCorrect: false },
      { text: 'No es obligatorio si está iluminado', isCorrect: false },
    ],
  },
  {
    prompt: 'Si circulando por la noche encuentra a otro vehículo de frente, debe...',
    explanation: 'Apagar las luces largas y poner las cortas para no deslumbrarle. Si le deslumbran, NO mire los faros: fije la vista en la línea derecha de la calzada.',
    category: 'ROAD_SAFETY',
    difficulty: 1,
    isTrap: false,
    tags: ['noche', 'luces'],
    options: [
      { text: 'Mantener las luces largas', isCorrect: false },
      { text: 'Apagar las largas y usar las cortas', isCorrect: true },
      { text: 'Tocar el claxon', isCorrect: false },
      { text: 'Apagar todas las luces', isCorrect: false },
    ],
  },
  {
    prompt: 'En condiciones de lluvia intensa o niebla densa, ¿qué luces debe llevar?',
    explanation: 'Luces de cruce obligatoriamente. Las antiniebla delanteras son opcionales (recomendadas) y las TRASERAS solo en niebla densa, lluvia intensa o nieve.',
    category: 'ROAD_SAFETY',
    difficulty: 3,
    isTrap: true,
    tags: ['niebla', 'lluvia', 'luces'],
    options: [
      { text: 'Solo posición', isCorrect: false },
      { text: 'Luces de cruce y, si procede, antiniebla', isCorrect: true },
      { text: 'Luces largas para ver mejor', isCorrect: false },
      { text: 'Antiniebla traseras siempre', isCorrect: false },
    ],
  },
];
