import type { QuestionCategory } from '../src/generated/prisma/client';
import type { SeedQuestion } from './seed-questions.js';

export const EXTRA_QUESTIONS: SeedQuestion[] = [
  // ─── VELOCIDAD ───────────────────────────────────────────────────────
  {
    prompt: 'Un turismo con remolque cuyo peso máximo autorizado supera los 750 kg, ¿a qué velocidad máxima puede circular en autopista?',
    explanation: 'Los turismos con remolque de MMA > 750 kg tienen limitada la velocidad a 80 km/h en autopistas y autovías. Es una trampa muy común: no es 90 ni 100.',
    category: 'SPEED' as QuestionCategory,
    difficulty: 4,
    isTrap: true,
    tags: ['velocidad', 'remolque', 'autopista'],
    options: [
      { text: '80 km/h', isCorrect: true },
      { text: '90 km/h', isCorrect: false },
      { text: '100 km/h', isCorrect: false },
      { text: '70 km/h', isCorrect: false },
    ],
  },
  {
    prompt: 'En un tramo en obras señalizado con límite de 40 km/h, ¿puedes rebasar esa velocidad para adelantar a un vehículo lento?',
    explanation: 'Los límites específicos señalizados —como los de obras— no pueden rebasarse en ningún caso, ni siquiera para adelantar. Solo se puede rebasar el límite genérico en 20 km/h al adelantar.',
    category: 'SPEED' as QuestionCategory,
    difficulty: 3,
    isTrap: true,
    tags: ['velocidad', 'obras', 'adelantamiento'],
    options: [
      { text: 'No, los límites específicos no pueden rebasarse', isCorrect: true },
      { text: 'Sí, puedo superar en 20 km/h', isCorrect: false },
      { text: 'Sí, si la calzada está libre', isCorrect: false },
      { text: 'Solo en autopistas', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuál es la velocidad mínima que debes mantener en el carril izquierdo de una autopista con dos o más carriles por sentido?',
    explanation: 'En autopistas con dos o más carriles, el carril izquierdo es de adelantamiento. La velocidad mínima es el 50% del límite máximo (60 km/h si el límite es 120 km/h). No puedes circular por él de forma continua a baja velocidad.',
    category: 'SPEED' as QuestionCategory,
    difficulty: 4,
    isTrap: false,
    tags: ['velocidad', 'mínima', 'autopista', 'carril izquierdo'],
    options: [
      { text: '60 km/h (50 % del límite máximo)', isCorrect: true },
      { text: '80 km/h', isCorrect: false },
      { text: '90 km/h', isCorrect: false },
      { text: 'No existe velocidad mínima', isCorrect: false },
    ],
  },
  {
    prompt: 'En una zona 20 urbana con plataforma única compartida por peatones y vehículos, ¿cuál es el límite?',
    explanation: 'Las calles con plataforma única (al mismo nivel acera y calzada) tienen límite de 20 km/h. Los peatones tienen preferencia absoluta.',
    category: 'SPEED' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['velocidad', 'urbano', '20', 'plataforma única'],
    options: [
      { text: '20 km/h', isCorrect: true },
      { text: '30 km/h', isCorrect: false },
      { text: '10 km/h', isCorrect: false },
      { text: '50 km/h', isCorrect: false },
    ],
  },
  {
    prompt: 'En una vía urbana con dos o más carriles por sentido, ¿cuál es la velocidad máxima genérica?',
    explanation: 'Las vías urbanas con dos o más carriles por sentido tienen el límite genérico de 50 km/h. El límite de 30 km/h aplica solo cuando hay un único carril por sentido.',
    category: 'SPEED' as QuestionCategory,
    difficulty: 3,
    isTrap: true,
    tags: ['velocidad', 'urbano', '50', 'multicarril'],
    options: [
      { text: '50 km/h', isCorrect: true },
      { text: '30 km/h', isCorrect: false },
      { text: '40 km/h', isCorrect: false },
      { text: '60 km/h', isCorrect: false },
    ],
  },

  // ─── SEÑALES ─────────────────────────────────────────────────────────
  {
    prompt: 'Una señal circular con borde rojo y fondo blanco que muestra el número 50, ¿qué indica?',
    explanation: 'Las señales de prohibición son circulares con borde rojo. La que muestra un número indica la velocidad máxima permitida a partir de ese punto hasta que otra señal la modifique.',
    category: 'SIGNALS' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['señales', 'prohibición', 'velocidad'],
    options: [
      { text: 'Velocidad máxima 50 km/h', isCorrect: true },
      { text: 'Velocidad mínima 50 km/h', isCorrect: false },
      { text: 'Fin del límite de 50 km/h', isCorrect: false },
      { text: 'Recomendación de 50 km/h', isCorrect: false },
    ],
  },
  {
    prompt: 'Una señal triangular con fondo blanco, borde rojo y un dibujo en su interior, ¿a qué tipo corresponde?',
    explanation: 'Las señales de advertencia de peligro son triangulares, con fondo blanco (o amarillo en algunos países), borde rojo y la imagen del peligro en el interior.',
    category: 'SIGNALS' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['señales', 'peligro', 'triángulo'],
    options: [
      { text: 'Señal de peligro', isCorrect: true },
      { text: 'Señal de prohibición', isCorrect: false },
      { text: 'Señal de obligación', isCorrect: false },
      { text: 'Señal informativa', isCorrect: false },
    ],
  },
  {
    prompt: 'Las señales de obligación tienen forma...',
    explanation: 'Las señales de obligación son circulares con fondo azul. Indican una conducta obligatoria (p.ej. dirección obligatoria, velocidad mínima).',
    category: 'SIGNALS' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['señales', 'obligación', 'azul'],
    options: [
      { text: 'Circular con fondo azul', isCorrect: true },
      { text: 'Circular con borde rojo', isCorrect: false },
      { text: 'Cuadrada con fondo azul', isCorrect: false },
      { text: 'Triangular con borde rojo', isCorrect: false },
    ],
  },
  {
    prompt: 'Una señal octogonal roja con la palabra STOP obliga a...',
    explanation: 'La señal de STOP obliga a detener completamente el vehículo (velocidad cero) antes de la línea de detención o del cruce, aunque no vengan otros vehículos.',
    category: 'SIGNALS' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['señales', 'STOP', 'detención'],
    options: [
      { text: 'Detener completamente el vehículo y ceder el paso', isCorrect: true },
      { text: 'Reducir la velocidad y ceder el paso', isCorrect: false },
      { text: 'Detenerse solo si hay vehículos', isCorrect: false },
      { text: 'Ceder el paso sin detenerse', isCorrect: false },
    ],
  },
  {
    prompt: 'Una señal triangular de "Ceda el paso" (invertida, vértice hacia abajo) obliga a...',
    explanation: 'La señal de Ceda el paso obliga a reducir la velocidad y estar dispuesto a detenerse para ceder el paso a los vehículos que circulan por la vía a la que se accede. No exige detención completa si la vía está libre.',
    category: 'SIGNALS' as QuestionCategory,
    difficulty: 2,
    isTrap: true,
    tags: ['señales', 'ceda el paso', 'prioridad'],
    options: [
      { text: 'Ceder el paso; detenerse solo si es necesario', isCorrect: true },
      { text: 'Detenerse completamente siempre', isCorrect: false },
      { text: 'Acelerar para no obstaculizar', isCorrect: false },
      { text: 'Tiene el mismo significado que STOP', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué forma tienen las señales de fin de prohibición o restricción?',
    explanation: 'Las señales de fin de prohibición son circulares con fondo blanco y una o varias rayas diagonales negras o grises cruzando el número o símbolo.',
    category: 'SIGNALS' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['señales', 'fin prohibición'],
    options: [
      { text: 'Circular con rayas cruzadas sobre el símbolo', isCorrect: true },
      { text: 'Triangular con borde blanco', isCorrect: false },
      { text: 'Cuadrada con fondo verde', isCorrect: false },
      { text: 'Rectangular con flecha', isCorrect: false },
    ],
  },

  // ─── PRIORIDAD ───────────────────────────────────────────────────────
  {
    prompt: 'Llegas a una intersección sin señalizar y a tu derecha viene otro vehículo. ¿Quién tiene prioridad?',
    explanation: 'En intersecciones sin señalizar ni regular, tiene prioridad el vehículo que viene por la derecha. Esta es la norma general de prioridad de paso.',
    category: 'PRIORITY' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['prioridad', 'intersección', 'derecha'],
    options: [
      { text: 'El vehículo que viene por la derecha', isCorrect: true },
      { text: 'El vehículo que llegó primero', isCorrect: false },
      { text: 'El vehículo que va más rápido', isCorrect: false },
      { text: 'El que circula por la vía más ancha', isCorrect: false },
    ],
  },
  {
    prompt: 'Un vehículo de emergencias con sirena y luz azul encendida se aproxima. ¿Qué debes hacer?',
    explanation: 'Los vehículos prioritarios (ambulancias, bomberos, policía) con señales acústicas y luminosas tienen prioridad absoluta. Debes ceder el paso, apartarte lo antes posible y no obstruir su avance.',
    category: 'PRIORITY' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['prioridad', 'emergencias', 'ambulancia'],
    options: [
      { text: 'Ceder el paso y apartarte a la derecha', isCorrect: true },
      { text: 'Mantener la velocidad para no frenar su avance', isCorrect: false },
      { text: 'Detenerte en el carril sin moverte', isCorrect: false },
      { text: 'Solo ceder si va en tu mismo sentido', isCorrect: false },
    ],
  },
  {
    prompt: 'En una rotonda (glorieta), ¿quién tiene prioridad por norma general?',
    explanation: 'En España, los vehículos que ya circulan dentro de la glorieta tienen prioridad sobre los que pretenden entrar, salvo que haya señales que indiquen lo contrario.',
    category: 'PRIORITY' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['prioridad', 'glorieta', 'rotonda'],
    options: [
      { text: 'Los que circulan dentro de la glorieta', isCorrect: true },
      { text: 'Los que entran a la glorieta', isCorrect: false },
      { text: 'El que viene por la derecha del que entra', isCorrect: false },
      { text: 'Depende del tamaño de la glorieta', isCorrect: false },
    ],
  },
  {
    prompt: 'Un conductor que circula por una vía principal llega a un cruce con una vía secundaria señalizada con "Ceda el paso". ¿Quién tiene prioridad?',
    explanation: 'La señal "Ceda el paso" en la vía secundaria indica que esos conductores deben ceder el paso a los de la vía principal. Los de la vía principal tienen prioridad.',
    category: 'PRIORITY' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['prioridad', 'vía principal', 'ceda el paso'],
    options: [
      { text: 'El conductor de la vía principal', isCorrect: true },
      { text: 'El conductor de la vía secundaria', isCorrect: false },
      { text: 'El que viene por la derecha', isCorrect: false },
      { text: 'El que lleva mayor velocidad', isCorrect: false },
    ],
  },
  {
    prompt: '¿Los peatones tienen prioridad sobre los vehículos en todos los pasos de peatones señalizados?',
    explanation: 'Sí. En los pasos para peatones debidamente señalizados, los conductores están obligados a ceder el paso a los peatones que se dispongan a cruzar o ya estén cruzando.',
    category: 'PRIORITY' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['prioridad', 'peatones', 'paso de cebra'],
    options: [
      { text: 'Sí, el conductor debe ceder el paso siempre', isCorrect: true },
      { text: 'Solo si el peatón está ya en el paso', isCorrect: false },
      { text: 'Solo si hay señal luminosa en verde para peatones', isCorrect: false },
      { text: 'No, el vehículo tiene prioridad si va rápido', isCorrect: false },
    ],
  },
  {
    prompt: '¿Tienen prioridad los ciclistas que circulan por un carril bici protegido respecto a los vehículos que giran para entrar en una calle?',
    explanation: 'Sí. Los vehículos que giran para entrar o salir de una vía deben ceder el paso a los ciclistas que circulan en el mismo sentido o en sentido contrario por un carril bici.',
    category: 'PRIORITY' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['prioridad', 'ciclistas', 'carril bici'],
    options: [
      { text: 'Sí, el ciclista tiene prioridad', isCorrect: true },
      { text: 'No, el vehículo a motor tiene siempre prioridad', isCorrect: false },
      { text: 'Solo si el ciclista lleva casco', isCorrect: false },
      { text: 'Solo si el carril bici está pintado de verde', isCorrect: false },
    ],
  },

  // ─── ADELANTAMIENTOS ─────────────────────────────────────────────────
  {
    prompt: 'Para adelantar, ¿cuándo está permitido invadir el carril contrario?',
    explanation: 'Puedes invadir el carril contrario para adelantar solo si la calzada es visible y libre en suficiente distancia, y la línea de separación es discontinua (o hay señal que lo autorice). Nunca si hay línea continua.',
    category: 'OVERTAKING' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['adelantamiento', 'carril contrario', 'línea discontinua'],
    options: [
      { text: 'Cuando la calzada está libre y hay línea discontinua', isCorrect: true },
      { text: 'Siempre que el vehículo de delante vaya despacio', isCorrect: false },
      { text: 'Nunca está permitido', isCorrect: false },
      { text: 'Solo en vías de doble sentido con arcén', isCorrect: false },
    ],
  },
  {
    prompt: '¿Está prohibido adelantar en un paso a nivel sin barreras?',
    explanation: 'Sí. Los pasos a nivel sin barreras son zonas de adelantamiento prohibido, al igual que los pasos para peatones, curvas, cimas de montaña y túneles, entre otros.',
    category: 'OVERTAKING' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['adelantamiento', 'paso a nivel', 'prohibición'],
    options: [
      { text: 'Sí, está prohibido', isCorrect: true },
      { text: 'No, si el tren no está a la vista', isCorrect: false },
      { text: 'Solo está prohibido de noche', isCorrect: false },
      { text: 'Solo si hay señal específica', isCorrect: false },
    ],
  },
  {
    prompt: 'Al adelantar, ¿qué distancia lateral mínima debes guardar respecto al vehículo adelantado?',
    explanation: 'El Reglamento General de Circulación no fija un número exacto de metros, pero sí exige una distancia lateral suficiente para evitar todo peligro. Para ciclistas se recomienda 1,5 m. La clave es "suficiente para evitar todo riesgo".',
    category: 'OVERTAKING' as QuestionCategory,
    difficulty: 3,
    isTrap: true,
    tags: ['adelantamiento', 'distancia lateral', 'ciclistas'],
    options: [
      { text: 'La suficiente para evitar todo peligro (≥ 1,5 m al adelantar ciclistas)', isCorrect: true },
      { text: 'Exactamente 1 metro siempre', isCorrect: false },
      { text: 'Al menos 2 metros en todo caso', isCorrect: false },
      { text: 'No hay distancia mínima establecida', isCorrect: false },
    ],
  },
  {
    prompt: 'Cuando vas a ser adelantado, ¿debes acelerar?',
    explanation: 'No. El vehículo adelantado NO debe acelerar mientras dure la maniobra. Debe mantener su velocidad o incluso reducirla para facilitar el adelantamiento.',
    category: 'OVERTAKING' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['adelantamiento', 'ser adelantado'],
    options: [
      { text: 'No, debes mantener o reducir la velocidad', isCorrect: true },
      { text: 'Sí, para que el adelantamiento sea más rápido', isCorrect: false },
      { text: 'Solo si la vía tiene más de 8 metros de ancho', isCorrect: false },
      { text: 'Solo en autopistas', isCorrect: false },
    ],
  },
  {
    prompt: '¿Se puede adelantar por la derecha en España?',
    explanation: 'En general no. Está prohibido adelantar por la derecha, salvo excepciones: cuando el conductor de delante ha indicado que va a girar a la izquierda y hay espacio suficiente, o en retenciones donde el carril de la derecha avanza más rápido.',
    category: 'OVERTAKING' as QuestionCategory,
    difficulty: 3,
    isTrap: true,
    tags: ['adelantamiento', 'derecha', 'excepciones'],
    options: [
      { text: 'Solo en casos excepcionales (retenciones, giro a la izquierda del de delante)', isCorrect: true },
      { text: 'Siempre que haya espacio', isCorrect: false },
      { text: 'Nunca bajo ningún concepto', isCorrect: false },
      { text: 'Solo en vías urbanas', isCorrect: false },
    ],
  },
  {
    prompt: '¿En qué lugar está prohibido adelantar por línea continua en el centro de la calzada?',
    explanation: 'La línea longitudinal continua prohíbe adelantar o cambiar de carril cuando separa los sentidos de la marcha. Cruzarla o circular sobre ella está prohibido.',
    category: 'OVERTAKING' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['adelantamiento', 'línea continua'],
    options: [
      { text: 'Cuando hay línea continua separando los sentidos', isCorrect: true },
      { text: 'Solo en curvas', isCorrect: false },
      { text: 'Solo en autopistas', isCorrect: false },
      { text: 'Nunca, la línea continua solo es indicativa', isCorrect: false },
    ],
  },

  // ─── GLORIETAS ───────────────────────────────────────────────────────
  {
    prompt: 'Para salir de una glorieta, ¿cuándo debes usar el intermitente derecho?',
    explanation: 'Debes poner el intermitente derecho antes de la salida que precede a la tuya, para indicar tu intención de abandonar la glorieta. Algunos conductores lo activan justo al pasar la salida anterior.',
    category: 'ROUNDABOUTS' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['glorieta', 'intermitente', 'salida'],
    options: [
      { text: 'Antes de llegar a la salida que vas a tomar', isCorrect: true },
      { text: 'Al entrar en la glorieta', isCorrect: false },
      { text: 'No es obligatorio usar el intermitente', isCorrect: false },
      { text: 'Cuando ya estás en la salida elegida', isCorrect: false },
    ],
  },
  {
    prompt: 'En una glorieta con dos carriles, ¿en cuál debes circular si vas a tomar la primera salida (giro a la derecha)?',
    explanation: 'Si vas a salir en la primera o segunda salida (giro a la derecha o recto), lo recomendable es usar el carril exterior (derecho). Si vas a dar más de media vuelta (más salidas), el carril interior.',
    category: 'ROUNDABOUTS' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['glorieta', 'carril', 'multicarril'],
    options: [
      { text: 'Carril exterior (derecho)', isCorrect: true },
      { text: 'Carril interior (izquierdo)', isCorrect: false },
      { text: 'Cualquiera, no hay norma al respecto', isCorrect: false },
      { text: 'Solo si hay marca vial que lo indique', isCorrect: false },
    ],
  },
  {
    prompt: '¿Está permitido circular en sentido contrario dentro de una glorieta?',
    explanation: 'No. Las glorietas en España son de sentido único (antihorario). Circular en sentido contrario es una infracción muy grave.',
    category: 'ROUNDABOUTS' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['glorieta', 'sentido', 'prohibición'],
    options: [
      { text: 'No, las glorietas son de sentido único antihorario', isCorrect: true },
      { text: 'Sí, si la glorieta está vacía', isCorrect: false },
      { text: 'Solo con vehículos de emergencias', isCorrect: false },
      { text: 'Sí, si las marcas viales lo permiten', isCorrect: false },
    ],
  },
  {
    prompt: 'Al entrar en una glorieta, el intermitente izquierdo se usa para indicar...',
    explanation: 'Al entrar en la glorieta con el intermitente izquierdo indicas que vas a seguir circulando por ella (no saldrás en la primera salida). Es opcional pero recomendable por seguridad.',
    category: 'ROUNDABOUTS' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['glorieta', 'intermitente izquierdo', 'entrada'],
    options: [
      { text: 'Que no vas a salir en la primera salida', isCorrect: true },
      { text: 'Que vas a girar a la izquierda fuera de la glorieta', isCorrect: false },
      { text: 'Que cedes el paso', isCorrect: false },
      { text: 'Nada, no se usa el intermitente al entrar', isCorrect: false },
    ],
  },
  {
    prompt: 'En una glorieta señalizada con "Ceda el paso" en sus entradas, ¿quién tiene prioridad?',
    explanation: 'La señal "Ceda el paso" en la entrada de una glorieta confirma que los vehículos que ya circulan dentro tienen prioridad. Los que entran deben ceder.',
    category: 'ROUNDABOUTS' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['glorieta', 'prioridad', 'ceda el paso'],
    options: [
      { text: 'Los vehículos que ya están dentro de la glorieta', isCorrect: true },
      { text: 'Los que entran, porque vienen por la derecha', isCorrect: false },
      { text: 'El más rápido', isCorrect: false },
      { text: 'Depende del número de carriles', isCorrect: false },
    ],
  },
  {
    prompt: '¿Puedes detenerte dentro de una glorieta para ceder el paso a un peatón?',
    explanation: 'Sí. Aunque en las glorietas los vehículos que circulan tienen prioridad sobre los que entran, los peatones en los pasos habilitados dentro o en las salidas de la glorieta tienen prioridad sobre los vehículos.',
    category: 'ROUNDABOUTS' as QuestionCategory,
    difficulty: 3,
    isTrap: true,
    tags: ['glorieta', 'peatones', 'paso de cebra'],
    options: [
      { text: 'Sí, los peatones en paso habilitado tienen prioridad', isCorrect: true },
      { text: 'No, dentro de la glorieta los vehículos siempre tienen prioridad', isCorrect: false },
      { text: 'Solo si el peatón ya está en el paso', isCorrect: false },
      { text: 'Solo en glorietas urbanas', isCorrect: false },
    ],
  },

  // ─── APARCAMIENTO ────────────────────────────────────────────────────
  {
    prompt: '¿A qué distancia mínima de un paso de peatones está prohibido estacionar?',
    explanation: 'Está prohibido estacionar a menos de 5 metros de un paso para peatones. Esto garantiza la visibilidad para peatones y conductores.',
    category: 'PARKING' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['aparcamiento', 'paso de peatones', 'distancia'],
    options: [
      { text: '5 metros', isCorrect: true },
      { text: '3 metros', isCorrect: false },
      { text: '10 metros', isCorrect: false },
      { text: '2 metros', isCorrect: false },
    ],
  },
  {
    prompt: 'En una calle de sentido único, ¿se puede aparcar en ambos lados de la calzada?',
    explanation: 'En calles de sentido único, generalmente se permite aparcar en ambos lados si no existe señalización que lo prohíba. La DGT lo permite siempre que quede espacio suficiente para la circulación.',
    category: 'PARKING' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['aparcamiento', 'sentido único', 'ambos lados'],
    options: [
      { text: 'Sí, si no hay señal que lo prohíba', isCorrect: true },
      { text: 'No, solo en el lado derecho', isCorrect: false },
      { text: 'No, solo en el lado izquierdo', isCorrect: false },
      { text: 'Solo si hay marca vial de aparcamiento', isCorrect: false },
    ],
  },
  {
    prompt: '¿A qué distancia mínima de una señal de parada de autobús está prohibido estacionar?',
    explanation: 'Está prohibido estacionar a menos de 10 metros de una señal de parada de autobús, tranvía o metro. Así el autobús puede acceder y los viajeros embarcar/desembarcar con seguridad.',
    category: 'PARKING' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['aparcamiento', 'parada bus', 'distancia'],
    options: [
      { text: '10 metros', isCorrect: true },
      { text: '5 metros', isCorrect: false },
      { text: '15 metros', isCorrect: false },
      { text: '3 metros', isCorrect: false },
    ],
  },
  {
    prompt: '¿Puedes estacionar sobre la acera aunque solo sea con las dos ruedas delanteras?',
    explanation: 'No. Está totalmente prohibido estacionar sobre las aceras, aunque sea parcialmente. Los vehículos deben estacionar completamente en la calzada o en zonas habilitadas.',
    category: 'PARKING' as QuestionCategory,
    difficulty: 2,
    isTrap: true,
    tags: ['aparcamiento', 'acera', 'prohibición'],
    options: [
      { text: 'No, está completamente prohibido', isCorrect: true },
      { text: 'Sí, si la acera tiene más de 3 metros de ancho', isCorrect: false },
      { text: 'Solo en zonas residenciales', isCorrect: false },
      { text: 'Sí, si el vehículo es de menos de 1.000 kg', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuándo se diferencia entre "parada" y "estacionamiento"?',
    explanation: '"Parada" es la inmovilización breve (hasta 2 min) sin abandonar el vehículo, para operaciones de carga/descarga de personas o cosas. "Estacionamiento" es dejar el vehículo más tiempo o sin conductor.',
    category: 'PARKING' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['aparcamiento', 'parada', 'estacionamiento', 'diferencia'],
    options: [
      { text: 'Parada: breve (≤2 min) sin abandonar vehículo; Estacionamiento: el resto', isCorrect: true },
      { text: 'Ambos significan lo mismo', isCorrect: false },
      { text: 'Parada es sin motor; Estacionamiento es con motor en marcha', isCorrect: false },
      { text: 'Solo depende del tiempo, no de si se abandona el vehículo', isCorrect: false },
    ],
  },
  {
    prompt: '¿A qué distancia mínima de una intersección está prohibido estacionar en zona urbana?',
    explanation: 'Está prohibido estacionar a menos de 5 metros del punto de intersección de las calzadas, para mantener la visibilidad en los cruces.',
    category: 'PARKING' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['aparcamiento', 'intersección', 'cruce'],
    options: [
      { text: '5 metros', isCorrect: true },
      { text: '3 metros', isCorrect: false },
      { text: '10 metros', isCorrect: false },
      { text: '8 metros', isCorrect: false },
    ],
  },

  // ─── ALCOHOL Y DROGAS ────────────────────────────────────────────────
  {
    prompt: '¿Cuál es la tasa máxima de alcohol en sangre para un conductor novel (menos de 2 años de carnet)?',
    explanation: 'Los conductores noveles (menos de 2 años con permiso), los que transportan mercancías peligrosas y los conductores profesionales tienen el límite reducido a 0,3 g/l en sangre (0,15 mg/l en aire).',
    category: 'ALCOHOL_DRUGS' as QuestionCategory,
    difficulty: 2,
    isTrap: true,
    tags: ['alcohol', 'novel', 'tasa', 'límite'],
    options: [
      { text: '0,3 g/l en sangre', isCorrect: true },
      { text: '0,5 g/l en sangre', isCorrect: false },
      { text: '0,8 g/l en sangre', isCorrect: false },
      { text: '0,1 g/l en sangre', isCorrect: false },
    ],
  },
  {
    prompt: 'La tasa máxima de alcohol permitida para conductores en general es...',
    explanation: 'Para conductores en general la tasa es de 0,5 g/l en sangre o 0,25 mg/l en aire espirado. Superarla es infracción grave o muy grave según el nivel.',
    category: 'ALCOHOL_DRUGS' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['alcohol', 'tasa', 'límite general'],
    options: [
      { text: '0,5 g/l en sangre / 0,25 mg/l en aire', isCorrect: true },
      { text: '0,8 g/l en sangre', isCorrect: false },
      { text: '0,3 g/l en sangre', isCorrect: false },
      { text: '1,0 g/l en sangre', isCorrect: false },
    ],
  },
  {
    prompt: '¿Puede la policía obligarte a someterte a una prueba de alcoholemia aunque no hayas cometido ninguna infracción?',
    explanation: 'Sí. Los agentes de tráfico pueden realizar controles preventivos de alcoholemia a cualquier conductor, sin necesidad de causa específica ni sospecha de infracción.',
    category: 'ALCOHOL_DRUGS' as QuestionCategory,
    difficulty: 2,
    isTrap: true,
    tags: ['alcohol', 'control', 'policía', 'obligatorio'],
    options: [
      { text: 'Sí, los controles preventivos son legales', isCorrect: true },
      { text: 'No, solo si hay sospecha de infracción', isCorrect: false },
      { text: 'Solo tras un accidente', isCorrect: false },
      { text: 'Solo de noche', isCorrect: false },
    ],
  },
  {
    prompt: '¿Las drogas como el cannabis afectan a la capacidad de conducir aunque no se note subjetivamente?',
    explanation: 'Sí. Las drogas —incluido el cannabis— pueden afectar los reflejos, la percepción del riesgo y el tiempo de reacción incluso horas después de su consumo y sin que el conductor lo note. Conducir bajo su influencia está prohibido.',
    category: 'ALCOHOL_DRUGS' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['drogas', 'cannabis', 'aptitud', 'reflejos'],
    options: [
      { text: 'Sí, aunque no se sienta el efecto subjetivamente', isCorrect: true },
      { text: 'No, solo si se nota el efecto', isCorrect: false },
      { text: 'Solo a altas dosis', isCorrect: false },
      { text: 'No afecta si se consumió hace más de 3 horas', isCorrect: false },
    ],
  },
  {
    prompt: '¿Negarse a la prueba de alcoholemia está penado?',
    explanation: 'Sí. Negarse a someterse a las pruebas de detección de alcohol o drogas constituye un delito contra la seguridad vial, con penas de prisión de 6 meses a 1 año.',
    category: 'ALCOHOL_DRUGS' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['alcohol', 'negativa', 'delito'],
    options: [
      { text: 'Sí, es un delito con pena de prisión', isCorrect: true },
      { text: 'No, es solo una infracción administrativa', isCorrect: false },
      { text: 'Solo es sanción económica', isCorrect: false },
      { text: 'No, tienes derecho a negarte', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuántos puntos se pierden por conducir con una tasa de alcohol superior a 0,5 g/l?',
    explanation: 'Conducir con una tasa de alcohol superior a la permitida supone la pérdida de 6 puntos del carné (si está entre 0,5 y 0,8 g/l) o 6 puntos también por encima de 0,8 (además de ser delito penal).',
    category: 'ALCOHOL_DRUGS' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['alcohol', 'puntos', 'carné'],
    options: [
      { text: '6 puntos', isCorrect: true },
      { text: '3 puntos', isCorrect: false },
      { text: '4 puntos', isCorrect: false },
      { text: '2 puntos', isCorrect: false },
    ],
  },

  // ─── DOCUMENTACIÓN ───────────────────────────────────────────────────
  {
    prompt: '¿Cada cuántos años se debe renovar el permiso de conducir B (turismo) para conductores de entre 30 y 65 años?',
    explanation: 'Para conductores entre 30 y 65 años, el permiso de conducir clase B se renueva cada 10 años. Para menores de 30, también 10 años. Para mayores de 65, cada 5 años.',
    category: 'DOCUMENTATION' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['documentación', 'permiso', 'renovación'],
    options: [
      { text: 'Cada 10 años', isCorrect: true },
      { text: 'Cada 5 años', isCorrect: false },
      { text: 'Cada 3 años', isCorrect: false },
      { text: 'No caduca', isCorrect: false },
    ],
  },
  {
    prompt: '¿Estás obligado a llevar el seguro de responsabilidad civil en vigor para circular?',
    explanation: 'Sí. El seguro obligatorio de responsabilidad civil (SOA) es imprescindible. Circular sin él es una infracción muy grave y puede suponer la retirada del vehículo.',
    category: 'DOCUMENTATION' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['documentación', 'seguro', 'obligatorio'],
    options: [
      { text: 'Sí, es obligatorio y sancionable si se incumple', isCorrect: true },
      { text: 'No, es voluntario', isCorrect: false },
      { text: 'Solo para vehículos de más de 10 años', isCorrect: false },
      { text: 'Solo fuera de ciudad', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué documento acredita que un vehículo ha pasado la Inspección Técnica de Vehículos (ITV)?',
    explanation: 'La pegatina de la ITV colocada en el parabrisas y el informe de inspección acreditan que el vehículo ha superado la ITV. Circular sin ITV en vigor es infracción grave.',
    category: 'DOCUMENTATION' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['documentación', 'ITV', 'inspección'],
    options: [
      { text: 'La pegatina ITV en el parabrisas y el informe de inspección', isCorrect: true },
      { text: 'Solo el permiso de circulación', isCorrect: false },
      { text: 'Solo la ficha técnica', isCorrect: false },
      { text: 'El seguro del vehículo', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué documento demuestra que eres el titular legal de un vehículo?',
    explanation: 'El permiso de circulación es el documento que acredita la titularidad del vehículo. La ficha técnica (tarjeta de inspección técnica) indica las características técnicas pero no la titularidad.',
    category: 'DOCUMENTATION' as QuestionCategory,
    difficulty: 2,
    isTrap: true,
    tags: ['documentación', 'permiso circulación', 'titularidad'],
    options: [
      { text: 'El permiso de circulación', isCorrect: true },
      { text: 'La ficha técnica', isCorrect: false },
      { text: 'El seguro del vehículo', isCorrect: false },
      { text: 'El recibo del IVTM (impuesto municipal)', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué ocurre si un agente te pide la documentación y la tienes en casa?',
    explanation: 'Si no llevas la documentación encima, el agente puede exigirte que la presentes en una dependencia policial o jefatura de tráfico en un plazo determinado (acreditación diferida). Puedes ser sancionado si no la presentas.',
    category: 'DOCUMENTATION' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['documentación', 'agente', 'acreditación diferida'],
    options: [
      { text: 'Debes presentarla posteriormente en dependencia policial', isCorrect: true },
      { text: 'No pasa nada si la tienes en regla', isCorrect: false },
      { text: 'Te detienen en el acto', isCorrect: false },
      { text: 'Se te retira el vehículo de inmediato', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuándo está obligado un turismo privado a pasar la primera ITV?',
    explanation: 'Los turismos nuevos deben pasar su primera ITV a los 4 años de su matriculación. Después, cada 2 años hasta los 10 años, y anualmente a partir de los 10 años.',
    category: 'DOCUMENTATION' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['ITV', 'primera', 'plazo', '4 años'],
    options: [
      { text: 'A los 4 años de matriculación', isCorrect: true },
      { text: 'Al año de matriculación', isCorrect: false },
      { text: 'A los 2 años de matriculación', isCorrect: false },
      { text: 'A los 5 años de matriculación', isCorrect: false },
    ],
  },

  // ─── SEGURIDAD VIAL ──────────────────────────────────────────────────
  {
    prompt: '¿Es obligatorio el uso del cinturón de seguridad en todas las plazas del vehículo?',
    explanation: 'Sí. Todos los ocupantes del vehículo, independientemente de la plaza que ocupen (delante o detrás), deben usar el cinturón de seguridad si el vehículo lo tiene instalado. El conductor es responsable de que los menores de 14 años lo usen.',
    category: 'ROAD_SAFETY' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['cinturón', 'obligatorio', 'seguridad'],
    options: [
      { text: 'Sí, en todas las plazas con cinturón disponible', isCorrect: true },
      { text: 'Solo en los asientos delanteros', isCorrect: false },
      { text: 'Solo en vías interurbanas', isCorrect: false },
      { text: 'Solo el conductor', isCorrect: false },
    ],
  },
  {
    prompt: '¿Puedes usar el teléfono móvil con auriculares mientras conduces?',
    explanation: 'No. Está prohibido usar el teléfono móvil mientras se conduce, incluso con auriculares o manos libres, si supone una distracción. Concretamente, sujetar el teléfono con la mano está prohibido. El uso de auriculares también está prohibido en España.',
    category: 'ROAD_SAFETY' as QuestionCategory,
    difficulty: 3,
    isTrap: true,
    tags: ['teléfono', 'distracción', 'auriculares'],
    options: [
      { text: 'No, los auriculares también están prohibidos al conducir', isCorrect: true },
      { text: 'Sí, si no se sostiene el teléfono con la mano', isCorrect: false },
      { text: 'Sí, en vías urbanas con límite de 30 km/h', isCorrect: false },
      { text: 'Solo está prohibido en autopistas', isCorrect: false },
    ],
  },
  {
    prompt: 'En caso de avería en autopista, ¿dónde debes colocarte mientras esperas ayuda?',
    explanation: 'Debes salir del vehículo por el lado que no da a la calzada, colocarte detrás de la barrera de contención o en zona segura fuera de la vía. Nunca te quedes en el carril de circulación ni en el arcén si puedes ir más allá de la barrera.',
    category: 'ROAD_SAFETY' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['avería', 'autopista', 'seguridad', 'posición'],
    options: [
      { text: 'Tras la barrera de contención, fuera de la calzada', isCorrect: true },
      { text: 'Dentro del vehículo con el cinturón puesto', isCorrect: false },
      { text: 'En el arcén, junto al vehículo', isCorrect: false },
      { text: 'En el carril de circulación señalizando el obstáculo', isCorrect: false },
    ],
  },
  {
    prompt: '¿A qué distancia mínima deben colocarse los triángulos de emergencia en autopista?',
    explanation: 'En autopistas y autovías, los triángulos deben colocarse a 50 metros del vehículo (visible desde 100 m). En carretera convencional, a 50 metros delante y detrás. En ciudad, si se puede, también a 50 m.',
    category: 'ROAD_SAFETY' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['triángulos', 'emergencia', 'distancia', 'autopista'],
    options: [
      { text: '50 metros', isCorrect: true },
      { text: '25 metros', isCorrect: false },
      { text: '100 metros', isCorrect: false },
      { text: '10 metros', isCorrect: false },
    ],
  },
  {
    prompt: 'La fatiga al volante, ¿puede provocar microsueños?',
    explanation: 'Sí. La fatiga extrema puede provocar microsueños (episodios de sueño de 2 a 30 segundos) sin que el conductor sea consciente. A 120 km/h, un microsueño de 5 segundos supone recorrer 167 metros sin control.',
    category: 'ROAD_SAFETY' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['fatiga', 'microsueño', 'somnolencia'],
    options: [
      { text: 'Sí, son muy peligrosos porque el conductor no es consciente', isCorrect: true },
      { text: 'No, la fatiga solo alarga el tiempo de reacción', isCorrect: false },
      { text: 'Solo en conductores mayores de 60 años', isCorrect: false },
      { text: 'Solo de madrugada', isCorrect: false },
    ],
  },

  // ─── INTERSECCIONES ──────────────────────────────────────────────────
  {
    prompt: 'En un cruce sin señalizar, ¿qué vehículo tiene prioridad: el que viene por una vía pavimentada o el que viene por un camino de tierra?',
    explanation: 'Cuando una vía tiene pavimento firme y la otra no, el vehículo de la vía pavimentada tiene prioridad, aunque venga por la izquierda. Esta es una excepción a la regla general de la derecha.',
    category: 'INTERSECTIONS' as QuestionCategory,
    difficulty: 4,
    isTrap: true,
    tags: ['intersección', 'prioridad', 'pavimentada', 'camino'],
    options: [
      { text: 'El que circula por la vía pavimentada', isCorrect: true },
      { text: 'El que viene por la derecha, siempre', isCorrect: false },
      { text: 'El que lleva más velocidad', isCorrect: false },
      { text: 'El que llegó primero al cruce', isCorrect: false },
    ],
  },
  {
    prompt: 'Al girar a la izquierda en una intersección, ¿debes ceder el paso a los vehículos que vienen de frente?',
    explanation: 'Sí. Al girar a la izquierda en una intersección, el conductor debe ceder el paso a los vehículos que vienen en sentido contrario (de frente) antes de completar el giro.',
    category: 'INTERSECTIONS' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['intersección', 'giro izquierda', 'prioridad frente'],
    options: [
      { text: 'Sí, los vehículos de frente tienen prioridad', isCorrect: true },
      { text: 'No, el giro a izquierda no requiere ceder', isCorrect: false },
      { text: 'Solo si hay señal específica', isCorrect: false },
      { text: 'Solo en vías de alta velocidad', isCorrect: false },
    ],
  },
  {
    prompt: '¿En qué carril debes colocarte para girar a la derecha en una intersección?',
    explanation: 'Para girar a la derecha debes situarte en el carril más a la derecha antes de la intersección y realizar el giro lo más cerrado posible por la derecha.',
    category: 'INTERSECTIONS' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['intersección', 'giro derecha', 'carril'],
    options: [
      { text: 'En el carril más a la derecha', isCorrect: true },
      { text: 'En cualquier carril', isCorrect: false },
      { text: 'En el carril central', isCorrect: false },
      { text: 'En el carril izquierdo para mayor visibilidad', isCorrect: false },
    ],
  },
  {
    prompt: 'En un cruce regulado por semáforo en verde, ¿puedes entrar aunque no puedas salir por haber retención al otro lado?',
    explanation: 'No. Aunque el semáforo esté en verde, no debes entrar en el cruce si hay retención que te impide salir de él. Si lo haces y el semáforo cambia a rojo, estarás bloqueando el cruce para los vehículos de la otra dirección.',
    category: 'INTERSECTIONS' as QuestionCategory,
    difficulty: 3,
    isTrap: true,
    tags: ['intersección', 'semáforo', 'retención', 'bloqueo'],
    options: [
      { text: 'No, podrías bloquear el cruce', isCorrect: true },
      { text: 'Sí, el semáforo verde da prioridad absoluta', isCorrect: false },
      { text: 'Solo si la retención dura más de 2 minutos', isCorrect: false },
      { text: 'Sí, en calles de un solo carril', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué significa una flecha verde de giro en un semáforo rojo?',
    explanation: 'La flecha verde de giro indica que puedes realizar ese giro específico aunque el semáforo general esté en rojo, pero SIEMPRE cediendo el paso a peatones y vehículos que tengan vía libre.',
    category: 'INTERSECTIONS' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['intersección', 'semáforo', 'flecha verde'],
    options: [
      { text: 'Puedes girar en esa dirección cediendo el paso a peatones y otros vehículos', isCorrect: true },
      { text: 'Prioridad total, puedes girar sin ceder el paso', isCorrect: false },
      { text: 'Solo para vehículos de emergencias', isCorrect: false },
      { text: 'Debes esperar aunque nadie cruce', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué debes hacer si el semáforo está averiado (sin luz)?',
    explanation: 'Si el semáforo está apagado (averiado), el cruce pasa a comportarse como si no tuviera regulación. Debes aplicar las normas generales de prioridad: ceder el paso al que viene por la derecha en intersecciones sin señalizar.',
    category: 'INTERSECTIONS' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['intersección', 'semáforo apagado', 'avería'],
    options: [
      { text: 'Aplicar las normas generales de prioridad (derecha)', isCorrect: true },
      { text: 'Quien llegue primero tiene prioridad', isCorrect: false },
      { text: 'El más rápido tiene prioridad', isCorrect: false },
      { text: 'Detenerse indefinidamente hasta que funcione', isCorrect: false },
    ],
  },

  // ─── PRIMEROS AUXILIOS ───────────────────────────────────────────────
  {
    prompt: '¿Cuál es la secuencia correcta ante un accidente de tráfico?',
    explanation: 'La regla PAS: Proteger (señalizar el lugar, evitar nuevos accidentes), Avisar (llamar al 112) y Socorrer (prestar primeros auxilios sin agravar las lesiones).',
    category: 'FIRST_AID' as QuestionCategory,
    difficulty: 1,
    isTrap: false,
    tags: ['primeros auxilios', 'PAS', 'accidente'],
    options: [
      { text: 'Proteger, Avisar, Socorrer (PAS)', isCorrect: true },
      { text: 'Socorrer, Avisar, Proteger', isCorrect: false },
      { text: 'Avisar, Proteger, Socorrer', isCorrect: false },
      { text: 'Socorrer, Proteger, Avisar', isCorrect: false },
    ],
  },
  {
    prompt: '¿Debes mover a una persona accidentada si no sabes si tiene lesiones en la columna?',
    explanation: 'No. Si no sabes si hay lesión cervical o en la columna, NO debes mover al accidentado. Solo se mueve si hay riesgo de incendio o explosión inmediato. Mover mal a un herido medular puede provocar parálisis.',
    category: 'FIRST_AID' as QuestionCategory,
    difficulty: 2,
    isTrap: true,
    tags: ['primeros auxilios', 'columna', 'mover herido'],
    options: [
      { text: 'No, salvo riesgo de incendio o explosión', isCorrect: true },
      { text: 'Sí, siempre que el herido esté consciente', isCorrect: false },
      { text: 'Sí, hay que sacarlo del vehículo siempre', isCorrect: false },
      { text: 'Solo si está en la calzada', isCorrect: false },
    ],
  },
  {
    prompt: 'Si una persona está inconsciente pero respira, ¿en qué posición debes colocarla?',
    explanation: 'Coloca a la persona inconsciente pero que respira en posición lateral de seguridad (PLS): de lado, con la boca hacia abajo para evitar que se ahogue con vómitos o secreciones.',
    category: 'FIRST_AID' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['primeros auxilios', 'posición lateral', 'inconsciente'],
    options: [
      { text: 'Posición lateral de seguridad (de lado)', isCorrect: true },
      { text: 'Boca arriba con las piernas elevadas', isCorrect: false },
      { text: 'Sentado con la espalda recta', isCorrect: false },
      { text: 'Boca abajo con la cabeza girada', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cada cuántos segundos se realiza una compresión torácica en la RCP básica (adultos)?',
    explanation: 'En la RCP básica de adultos se realizan compresiones a un ritmo de 100-120 por minuto (aproximadamente 2 por segundo), con una profundidad de 5-6 cm. La relación es 30 compresiones por 2 insuflaciones.',
    category: 'FIRST_AID' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['primeros auxilios', 'RCP', 'compresiones'],
    options: [
      { text: '100-120 compresiones por minuto (~2 por segundo)', isCorrect: true },
      { text: '60 compresiones por minuto (1 por segundo)', isCorrect: false },
      { text: '50 compresiones por minuto', isCorrect: false },
      { text: '200 compresiones por minuto', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué debes hacer si una herida sangra abundantemente?',
    explanation: 'Ante una hemorragia abundante debes aplicar presión directa sobre la herida con un paño limpio, mantenerla constante y elevar el miembro afectado si es posible. No debes retirar el paño si se empapa: añade más encima.',
    category: 'FIRST_AID' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['primeros auxilios', 'hemorragia', 'presión'],
    options: [
      { text: 'Presión directa con paño limpio y elevar el miembro', isCorrect: true },
      { text: 'Aplicar un torniquete inmediatamente', isCorrect: false },
      { text: 'Lavar la herida con agua', isCorrect: false },
      { text: 'Dejar que la sangre fluya libremente', isCorrect: false },
    ],
  },
  {
    prompt: 'Llegas a un accidente y la víctima no respira. ¿Qué haces primero?',
    explanation: 'Si la víctima no respira: llama al 112, inclina la cabeza hacia atrás para abrir la vía aérea y empieza la RCP (30 compresiones + 2 insuflaciones) hasta que llegue ayuda o la persona recupere la respiración.',
    category: 'FIRST_AID' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['primeros auxilios', 'RCP', 'no respira'],
    options: [
      { text: 'Llamar al 112 e iniciar RCP inmediatamente', isCorrect: true },
      { text: 'Esperar a la ambulancia sin tocar a la víctima', isCorrect: false },
      { text: 'Darle agua para que recupere el conocimiento', isCorrect: false },
      { text: 'Moverla para estimularla', isCorrect: false },
    ],
  },

  // ─── MECÁNICA ────────────────────────────────────────────────────────
  {
    prompt: '¿Qué indica el testigo luminoso rojo con forma de batería en el cuadro de mandos?',
    explanation: 'El testigo de la batería en rojo indica que el sistema de carga no está funcionando correctamente. Puede ser un fallo en el alternador. Debes parar el vehículo en lugar seguro y no seguir conduciendo, ya que la batería se agotará.',
    category: 'MECHANICS' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['mecánica', 'batería', 'alternador', 'testigo'],
    options: [
      { text: 'Fallo en el sistema de carga (alternador)', isCorrect: true },
      { text: 'Batería completamente cargada', isCorrect: false },
      { text: 'Avería en el motor de arranque', isCorrect: false },
      { text: 'Solo indica que hay que recargar la batería', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué debes hacer si el testigo de presión de aceite se enciende mientras conduces?',
    explanation: 'Si se enciende el testigo de presión de aceite (aceite rojo), debes parar el vehículo de forma segura lo antes posible y apagar el motor. Continuar conduciendo puede causar daños irreparables en el motor por falta de lubricación.',
    category: 'MECHANICS' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['mecánica', 'aceite', 'testigo', 'presión'],
    options: [
      { text: 'Parar el vehículo y apagar el motor inmediatamente', isCorrect: true },
      { text: 'Añadir aceite en marcha', isCorrect: false },
      { text: 'Continuar hasta la próxima gasolinera', isCorrect: false },
      { text: 'Reducir la velocidad pero seguir', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué ocurre si conduces con los neumáticos desinflados?',
    explanation: 'Los neumáticos desinflados reducen la adherencia, aumentan la distancia de frenado, dificultan el control del vehículo y pueden provocar reventones a alta velocidad. Es una causa frecuente de accidentes graves.',
    category: 'MECHANICS' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['mecánica', 'neumáticos', 'presión', 'seguridad'],
    options: [
      { text: 'Reduce adherencia y aumenta la distancia de frenado', isCorrect: true },
      { text: 'Solo aumenta el consumo de combustible', isCorrect: false },
      { text: 'No afecta a la seguridad en velocidades bajas', isCorrect: false },
      { text: 'Mejora el agarre en mojado', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué es el ABS (Sistema Antibloqueo de Frenos)?',
    explanation: 'El ABS evita que las ruedas se bloqueen durante el frenado brusco, permitiendo mantener el control de dirección del vehículo. Con ABS se debe frenar con firmeza y sin soltar el freno, el propio sistema regula la presión.',
    category: 'MECHANICS' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['mecánica', 'ABS', 'frenos', 'antibloqueo'],
    options: [
      { text: 'Sistema que evita el bloqueo de ruedas y mantiene el control de dirección', isCorrect: true },
      { text: 'Sistema que frena automáticamente el vehículo', isCorrect: false },
      { text: 'Sistema que aumenta la potencia de frenada en seco', isCorrect: false },
      { text: 'Sistema que reduce el consumo en ciudad', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué es el aquaplaning?',
    explanation: 'El aquaplaning (o hidroplaneo) ocurre cuando una capa de agua se interpone entre el neumático y el asfalto, eliminando el contacto y por tanto el control del vehículo. Se produce especialmente a velocidades altas y con neumáticos desgastados.',
    category: 'MECHANICS' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['mecánica', 'aquaplaning', 'lluvia', 'adherencia'],
    options: [
      { text: 'Pérdida de adherencia por capa de agua entre neumático y asfalto', isCorrect: true },
      { text: 'Patinaje de ruedas en frío', isCorrect: false },
      { text: 'Sobreviraje en curvas mojadas', isCorrect: false },
      { text: 'Vibración del volante por desequilibrio de ruedas', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cada cuántos km se recomienda revisar la profundidad del dibujo de los neumáticos?',
    explanation: 'La ley exige un mínimo de 1,6 mm de profundidad del dibujo. Se recomienda revisarlos frecuentemente y cambiarlos cuando alcancen los 2-3 mm para mayor seguridad. Muchos expertos recomiendan revisarlos mensualmente.',
    category: 'MECHANICS' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['mecánica', 'neumáticos', 'dibujo', 'desgaste'],
    options: [
      { text: 'Al menos mensualmente o en cada revisión de taller', isCorrect: true },
      { text: 'Solo en la ITV', isCorrect: false },
      { text: 'Cada 100.000 km', isCorrect: false },
      { text: 'No es necesario revisarlos si no hay aviso del coche', isCorrect: false },
    ],
  },

  // ─── CONDUCCIÓN EFICIENTE ────────────────────────────────────────────
  {
    prompt: '¿Cuándo es más eficiente cambiar a una marcha superior?',
    explanation: 'Para una conducción eficiente, se recomienda cambiar a marcha superior entre 2.000 y 2.500 rpm en gasolina y entre 1.500 y 2.000 rpm en diésel. Circular a marchas cortas consume más combustible.',
    category: 'EFFICIENT_DRIVING' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['conducción eficiente', 'cambio de marcha', 'rpm'],
    options: [
      { text: 'A 2.000-2.500 rpm en gasolina y 1.500-2.000 en diésel', isCorrect: true },
      { text: 'A 4.000 rpm o más', isCorrect: false },
      { text: 'Lo más tarde posible para ganar potencia', isCorrect: false },
      { text: 'Solo cuando el motor lo pida (no hay norma)', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué factor influye más en el consumo de combustible a alta velocidad?',
    explanation: 'La resistencia aerodinámica crece con el cuadrado de la velocidad. A partir de 90-100 km/h, duplicar la velocidad cuadruplica la resistencia del viento, disparando el consumo. Es el factor más determinante a velocidades altas.',
    category: 'EFFICIENT_DRIVING' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['conducción eficiente', 'consumo', 'aerodinámica', 'velocidad'],
    options: [
      { text: 'La resistencia aerodinámica (crece con el cuadrado de la velocidad)', isCorrect: true },
      { text: 'La presión de los neumáticos', isCorrect: false },
      { text: 'El aire acondicionado', isCorrect: false },
      { text: 'El peso del vehículo', isCorrect: false },
    ],
  },
  {
    prompt: '¿El uso del aire acondicionado aumenta el consumo de combustible?',
    explanation: 'Sí. El compresor del aire acondicionado puede aumentar el consumo entre un 5% y un 25% dependiendo de las condiciones. En ciudad el impacto es mayor. A velocidades altas, en cambio, es más eficiente el A/C que llevar las ventanas abiertas (por la aerodinámica).',
    category: 'EFFICIENT_DRIVING' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['conducción eficiente', 'aire acondicionado', 'consumo'],
    options: [
      { text: 'Sí, puede aumentar el consumo entre un 5% y un 25%', isCorrect: true },
      { text: 'No, los coches modernos no se ven afectados', isCorrect: false },
      { text: 'Solo en coches diésel', isCorrect: false },
      { text: 'Solo si la temperatura exterior supera 40°C', isCorrect: false },
    ],
  },
  {
    prompt: '¿Cuál es la velocidad más eficiente para circular en autopista en un turismo convencional?',
    explanation: 'Generalmente la velocidad más eficiente se sitúa entre 90 y 110 km/h, donde el motor trabaja en su zona de mayor rendimiento y la resistencia aerodinámica aún no es excesiva. Por encima de 110-120 km/h el consumo se dispara.',
    category: 'EFFICIENT_DRIVING' as QuestionCategory,
    difficulty: 3,
    isTrap: false,
    tags: ['conducción eficiente', 'velocidad óptima', 'autopista'],
    options: [
      { text: 'Entre 90 y 110 km/h', isCorrect: true },
      { text: '120 km/h (el límite máximo)', isCorrect: false },
      { text: '60 km/h (marcha lenta = menos consumo)', isCorrect: false },
      { text: 'Depende solo de la cilindrada del motor', isCorrect: false },
    ],
  },
  {
    prompt: '¿Arrancar el motor y dejarlo calentando varios minutos antes de circular es una buena práctica?',
    explanation: 'No. Los motores modernos (gasolina y diésel) están diseñados para calentarse circulando suavemente. Dejarlo al ralentí mucho tiempo desperdicia combustible y puede dañar algunos componentes. Lo correcto es arrancar y circular de inmediato con suavidad.',
    category: 'EFFICIENT_DRIVING' as QuestionCategory,
    difficulty: 2,
    isTrap: true,
    tags: ['conducción eficiente', 'calentamiento', 'ralentí'],
    options: [
      { text: 'No, los motores modernos deben calentarse circulando suavemente', isCorrect: true },
      { text: 'Sí, siempre hay que calentar el motor al ralentí', isCorrect: false },
      { text: 'Solo en diésel y en invierno', isCorrect: false },
      { text: 'Sí, mejora la vida del motor en todos los casos', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué es la conducción anticipatoria?',
    explanation: 'La conducción anticipatoria (o predictiva) consiste en observar el tráfico con antelación para adaptar la velocidad de forma suave, evitando aceleraciones y frenadas bruscas. Reduce el consumo hasta un 15-20% y aumenta la seguridad.',
    category: 'EFFICIENT_DRIVING' as QuestionCategory,
    difficulty: 2,
    isTrap: false,
    tags: ['conducción eficiente', 'anticipatoria', 'predictiva'],
    options: [
      { text: 'Adaptar la velocidad suavemente anticipando el tráfico', isCorrect: true },
      { text: 'Ir siempre al límite de velocidad', isCorrect: false },
      { text: 'Usar el freno motor en vez de los frenos', isCorrect: false },
      { text: 'Evitar el uso de la primera marcha', isCorrect: false },
    ],
  },
  {
    prompt: '¿Llevar el depósito siempre lleno es una práctica eficiente?',
    explanation: 'No necesariamente. La gasolina o el gasóleo pesan entre 0,7 y 0,85 kg por litro. Llevar el depósito siempre al máximo añade peso innecesario que aumenta el consumo. Lo recomendable es no llenarlo del todo ni dejarlo demasiado bajo.',
    category: 'EFFICIENT_DRIVING' as QuestionCategory,
    difficulty: 3,
    isTrap: true,
    tags: ['conducción eficiente', 'depósito', 'peso', 'consumo'],
    options: [
      { text: 'No, el peso extra del combustible aumenta el consumo', isCorrect: true },
      { text: 'Sí, siempre es mejor llevar el depósito lleno', isCorrect: false },
      { text: 'Depende del tipo de motor', isCorrect: false },
      { text: 'Solo importa en trayectos de más de 500 km', isCorrect: false },
    ],
  },
  {
    prompt: '¿Qué efecto tiene circular con las ventanas abiertas a alta velocidad?',
    explanation: 'A alta velocidad (más de 80-90 km/h), llevar las ventanas abiertas aumenta la resistencia aerodinámica y por tanto el consumo, más que lo que ahorraría apagar el aire acondicionado. Por eso a alta velocidad es más eficiente el A/C.',
    category: 'EFFICIENT_DRIVING' as QuestionCategory,
    difficulty: 3,
    isTrap: true,
    tags: ['conducción eficiente', 'ventanas', 'aerodinámica', 'A/C'],
    options: [
      { text: 'Aumenta la resistencia aerodinámica y el consumo', isCorrect: true },
      { text: 'Siempre consume menos que el aire acondicionado', isCorrect: false },
      { text: 'No afecta al consumo', isCorrect: false },
      { text: 'Solo afecta si se abren las cuatro ventanas', isCorrect: false },
    ],
  },
];
